### ISSUE TITLE
No implementation found for void.com.unistyles

### ISSUE THREAD

**Issue by Randall71** [jpudysz/react-native-unistyles#108]
### Description

https://github.com/jpudysz/react-native-unistyles/assets/51382079/708a1e92-f8ce-4fce-a708-d5494f4e667c

### Steps to reproduce

1. Init a fresh project with official expo template
2. add react-native-unistyles
3. Build using EAS
4. Launch app and swith theme

### Unistyles version

^2.0.0-rc.4

### React Native version

0.72.6

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
I think I probably know what it is. Can you confirm that by EAS you bundled in release mode?

**Comment by jpudysz** [comment]
I'm gonna need more details as I'm not able to reproduce with my demo app.

```
eas build --platform android --local
```


https://github.com/jpudysz/react-native-unistyles/assets/9088288/f47cd048-f380-4032-b184-c8f89fe2cfc2

**Comment by jpudysz** [comment]
Also:

Here is my official repo for expo router:
https://github.com/jpudysz/react-native-unistyles-expo-router

Steps to reproduce:

1. Setup project
```
clone repo
upgrade unistyles to RC4
yarn expo prebuild

setup eas.json
```
2. Build project
```
eas build --platform android --local
```

https://github.com/jpudysz/react-native-unistyles/assets/9088288/570e0ea0-c9da-4a84-aa69-42e37468e4fb

Feel free to open with more details or steps to reproduce/repo.
