### ISSUE TITLE
No auto suggestions on stylesheet properties

### ISSUE THREAD

**Issue by monarcode** [jpudysz/react-native-unistyles#11]
**Observation**
When creating styles using the native Stylesheet, I get hints as I type for properties e.g fontFamily, color, etc! As seen in the image below
![image](https://github.com/jpudysz/react-native-unistyles/assets/61241222/e2a2e5f6-7b0f-4d03-9fd3-1ddf9a870bdd)

How ever, when creating styles using createStyles, I either only get suggestions for the first property only or none at all(see image below)
![image](https://github.com/jpudysz/react-native-unistyles/assets/61241222/fe3e3b65-734c-4fff-be24-878a3a7e43e8)

**Environment**
Node version: v18.15.0
Operating system: MacOS Sonoma
Editor: VSCode
Unistyles version: ^1.0.0-beta.1
Framework: Expo + typescript (expo router)

**File structure**

```

//styles.ts

import { breakpoints } from "constants/breakpoints";
import { theme } from "constants/theme";
import { createUnistyles } from "react-native-unistyles";

export const { useStyles, createStyles } = createUnistyles<
  typeof breakpoints,
  typeof theme
>(breakpoints);

export { theme };

```

```
// example usage

import { Text, View } from "components/base";
import { createStyles, useStyles } from "libs/styles";

export default function TabOneScreen() {
  const { styles } = useStyles(styleSheet);

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tab One</Text>
    </View>
  );
}

const styleSheet = createStyles((theme) => ({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.light,
  },
  title: {
    fontSize: 42,
    color: "black",
  }
}));

```

**Comment by jpudysz** [comment]
Fixed with #12 !
