### ISSUE TITLE
Calling synchronous methods on native modules is not supported in Chrome

### ISSUE THREAD

**Issue by sereda93** [jpudysz/react-native-unistyles#114]
### Description

I am using react-native-unistyles version 2.0.0 but have some problems when starting debug.

![image](https://github.com/jpudysz/react-native-unistyles/assets/2189429/d06309d3-24e4-4c4c-b356-37fb740eef66)

### Steps to reproduce

1. npm install react-native-unistyles
2. Follow the set up guide for react native
3. open devtools (Debug JS Remotely or Open Debugger(Flipper))

### Unistyles version

2.0.0

### React Native version

0.72.6

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey 👋
Library has JSI bindings, so `Debug JS Remotely` with Chrome won't work.

Also:

`Remote JS Debugging with Chrome is deprecated`

Source:

https://github.com/react-native-community/discussions-and-proposals/discussions/734

For Flipper:

```
Debugging React Native apps with Flipper is [deprecated in React Native 0.73](https://github.com/react-native-community/discussions-and-proposals/pull/641). We will eventually remove out-of-the box support for JS debugging via Flipper.
```

Source: 

https://reactnative.dev/docs/debugging?js-debugger=flipper

I'm not willing to support deprecated debugging methods, even though you're on version 0.72.

Few solutions:
- For expo use `Expo debugger` (`j` key) - I'm using it and I can confirm that it works out of the box
- For RN use New Debugger (I haven't try it yet)

Sources:
- https://reactnative.dev/docs/debugging
- https://docs.expo.dev/debugging/tools/
