### ISSUE TITLE
Breakpoints don't work when not using Theme

### ISSUE THREAD

**Issue by andylukmawan** [jpudysz/react-native-unistyles#121]
### Description

Breakpoints inside `createStylesheet()` don't work when the theme is not used / it's not returned as a function

🔴 can't work:
```js
const stylesheet = createStyleSheet({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: {
            sm: 'cyan',
            md: 'magenta'
        },
    },
};
```

🟢 working correctly:
```js
const stylesheet = createStyleSheet(() => ({
  container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: {
            sm: 'cyan',
            md: 'magenta'
        },
    },
}));
```

### Steps to reproduce

1. Try modif this [example](https://github.com/jpudysz/react-native-unistyles/blob/a4fed1860aed41186e194c7f30c54ec84f65ea09/examples/expo/src/examples/NoThemesScreen.tsx#L23)
2. Check switch to potrait & landscape mode on real device or emulator

### Snack or a link to a repository (optional)

https://github.com/jpudysz/react-native-unistyles/tree/main/examples/expo

### Unistyles version

2.0.0

### React Native version

0.73.0

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey 👋 

I have found the issue. There was acutally one less dependency in `useMemo`. 

Thanks!

I will release 2.0.1 shortly
