### ISSUE TITLE
theme from useStyes() without stylesheet assumes type as never

### ISSUE THREAD

**Issue by z1haze** [jpudysz/react-native-unistyles#126]
### Description

I am not sure if this is a setup issue on my part or not, however I am noticing that intellisense in my IDE is typing the theme object that comes from the useStyles return object as never.

Apologies if this is not legitimate, I'm just trying to help point out a possible bug

### Steps to reproduce

1. call useStyles without explicitly providing a stylesheet and destructure theme

### Unistyles version

2.0.1

### React Native version

0.72.6

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by z1haze** [comment]
![image](https://github.com/jpudysz/react-native-unistyles/assets/6024725/a9e84f9e-1d15-4bc3-85b5-f1190b51b7b3)

**Comment by RodzAlves** [comment]
Did you do the correct setup?

https://reactnativeunistyles.vercel.app/start/setup/

Take a look at session 
**3.3 Configure TypeScript**

**Comment by efoken** [comment]
Cannot reproduce, probably something is wrong with your setup.

**Comment by jpudysz** [comment]
Did you import this file anywhere in your app?

```tsx
import './unistyles'
```

or whatever your filename is?

**Comment by z1haze** [comment]
yes, in App.tsx. I'm able to use `theme` from the destructured object, and it even knows all of the fields from ts.. its just the intellisense things it is of type never.

**Comment by jpudysz** [comment]
Two more questions:

Can you try to import your themes without absolute aliased path?

What IDE are you using ?

**Comment by z1haze** [comment]
I'm using webstorm. I will attempt this tomorrow, I've left my work machine for the night!

**Comment by jpudysz** [comment]
No worries, we will find the root cause ☺️

**Comment by z1haze** [comment]
Hey all, I made the update as requested to make the theme imports be relative paths, and there was no change here. Intellisense still claims to be `never` however I don't want to mistake you in claming that the typescript isn't working properly, because it does work. It is just very strange that is says never in intellisense.

![image](https://github.com/jpudysz/react-native-unistyles/assets/6024725/60becf2b-12fa-492e-a276-2c50df212509)

**Comment by jpudysz** [comment]
Is it possible to get minimal repo with repro? I need to see the whole picture.

**Comment by z1haze** [comment]
I can see about tomorrow starting a brand new expo project and seeing if it occurs. But fwiw, I am using expo 49 in webstorm and ts version 5.2.2 i think. I'm not on that machine right now but I do believe that is the version

**Comment by jpudysz** [comment]
I just want to confirm the issue and detect if this is machine / setup / unistyles core.

Thanks!

**Comment by jpudysz** [comment]
Hey, any update? Is this somehow related to: https://github.com/jpudysz/react-native-unistyles/discussions/133 ?

**Comment by jpudysz** [comment]
Hey @z1haze, I haven't heard from you for the past 7 days. Feel free to reopen this issue when you provide more information. Thanks!

**Comment by z1haze** [comment]
Apologies, I've been swamped. Once I get a moment to breathe ill create a separate project and try to replicate!

**Comment by jpudysz** [comment]
Sorry to hear that. Take your time

**Comment by mzaien** [comment]
I think I new what is the issue because I had it this week, if the unistyles type override was using ts `type` instead of `interface` this issue happens I noticed that because my eslint converts everything into a type 

```ts
// override library types
declare module 'react-native-unistyles' {
    // for some reason typing does not work unless we used an interface
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    export interface UnistylesThemes extends AppThemes {}
}
```

**Comment by jpudysz** [comment]
Thanks for posting it. Interface is required by TypeScript itself. Maybe that was the issue! 🙏

**Comment by z1haze** [comment]
We were already using an interface like described in the docs. The issue persists

**Comment by jpudysz** [comment]
It shouldn't. Many ppl are using unistyles without the issue. 

It must be something local, hard to guess. I need a minimal repo to help

**Comment by efoken** [comment]
Must be locally, I don’t have any problems.

**Comment by z1haze** [comment]
We've just learned to deal with it. Also its quite frustrating to get replies like "other people don't have issues". I don't see how that's contributing to the discussion. I didn't report this issue because I thought it would be fun to make up a problem :(. We run expo v51, (before it was 50, and before that it was 49), with react navigation, and a handful of other libraries.

There is some weird bug somewhere that webstorm's intellisense picks up on and infers the object as type never, while at the same time clearly knowing what the value of the object is. It is very strange, as you can see here in the screenshot.
![image](https://github.com/jpudysz/react-native-unistyles/assets/6024725/efc7a0ae-4491-4d7c-b58d-77fc31b8b13b)

**Comment by jpudysz** [comment]
I just meant that it's your unique issue, as you're only reporting it. I'm also using unistyles in multiple projects and I didn't get such weird types across any IDEs. 

You need to also understand that's frustrating to me as there is no reproduction and there is now way to help. This is typescript feature to extend someone's type it's not a blacboxed magic from unistyles.

**Comment by DaltonPelkey** [comment]
@jpudysz Here is a repro: https://github.com/DaltonPelkey/UnistyleRepro

Not sure if it is a Typescript issue or just general behavior, but once the theme object reaches a certain size the type defaults to `never`. See in the repo where Unistyles is configured the recommended way. In App.tsx the type of theme reads correctly. However, if you uncomment a single value in `lightTheme` it changes to `never`. If seemingly no one else is experiencing this then it leads me to believe that it is a Typescript issue.

If you swap out the declaration with the one commented out, it will then default to the explicit type of `UnistylesTheme` rather than `never`. This is my recommended fix for this specific issue.

Out of curiosity what IDEs have you been testing on, and how large have the theme objects been?

With 12 theme properties:
![image](https://github.com/jpudysz/react-native-unistyles/assets/9933256/5dc9ba29-75af-49ab-842c-2e5322272527)

With 13:
![image](https://github.com/jpudysz/react-native-unistyles/assets/9933256/e9b3612a-a52d-4c26-a706-04e2053eb4d0)

With 13 -and- my declaration code:
![image](https://github.com/jpudysz/react-native-unistyles/assets/9933256/64aebccc-8fb3-4fab-bb55-685092525ab9)

**Comment by DaltonPelkey** [comment]
> Btw, do you use bundled typescript from node_modules? Maybe you have some older version globally installed.

Just updated to the latest 5.4.5 and still the same issue. Let me know what you think of the repro

**Comment by DaltonPelkey** [comment]
Just to point out as well, most of the Unistyle methods also return theme of type `never` (rather than an explicit type):

![image](https://github.com/jpudysz/react-native-unistyles/assets/9933256/99e6a083-2c9d-40cb-bb4d-eab4eddf71f7)

![image](https://github.com/jpudysz/react-native-unistyles/assets/9933256/b2a77db7-dde3-4ad2-a007-8fb5cddb1537)

![image](https://github.com/jpudysz/react-native-unistyles/assets/9933256/780ab0f9-076d-4941-b34f-e048ee778f64)

**Comment by z1haze** [comment]
Thanks @DaltonPelkey for making a repro. so @jpudysz are you saying that you cannot observe this behavior with his repo? I just cloned it into a new project and am able to observe exactly what he's shown.

Also I believe that if this were an issue exclusive to typescript, or exclusive to typescript and webstorm, we would be observing this across all sorts of libraries and scenarios. The fact remains though that this only occurs with unistyles. Hopefully the repro repo provided will help them get to the bottom if it and fix it.

**Comment by jpudysz** [comment]
I can't repro. What I've done:

1. Download repo
2. yarn install
3. Open in VSC

![theme](https://github.com/jpudysz/react-native-unistyles/assets/9088288/eda274e7-0704-496f-ae6f-75b5fcbe9302)

4.  Check TS popup

![hint](https://github.com/jpudysz/react-native-unistyles/assets/9088288/f60f341c-c04e-4ed8-aa7c-6dbaaa630cab)

5. Uncomment all props from theme type

![all-props](https://github.com/jpudysz/react-native-unistyles/assets/9088288/8f9300f7-b550-49eb-856f-beaba672a6ca)

6. Add new props:

![xxx](https://github.com/jpudysz/react-native-unistyles/assets/9088288/5749b5b1-312f-43c1-8f55-9b2bc0ec1acb)

7. Repeat in WS (works the same)

![image](https://github.com/jpudysz/react-native-unistyles/assets/9088288/2b1502a6-b28c-4012-831a-ada9193aca23)

**Comment by DaltonPelkey** [comment]
I'm confused. You just sent a screenshot of the repro working on Webstorm. The intellisense on the object is not the issue. We are only referring to the `never` preview type

**Comment by jpudysz** [comment]
So, the issue is that WS previews the theme type as 'never'?

It seems that the issue comes from Webstorm TypeScript engine, as it's not visible in any other editor.
To fix it, you need to enable `Use types from server` setting which will use TypeScript Language Service.

More here:

https://www.jetbrains.com/help/webstorm/typescript-support.html#ws_ts_use_ts_service_checkbox
scroll to section 5 (3rd list item)

> By default, the checkbox is cleared so type evaluation, resolution, code inspections and refactorings are based on the type  information from the WebStorm internal TypeScript engine.
 
>This default behavior may result in performance issues and in bugs in type resolution because the type evaluation algorithm that the TypeScript Language Service uses differs from the algorithm of the TypeScript Compiler. Selecting the checkbox may help avoid these problems.

**Comment by z1haze** [comment]
> So, the issue is that WS previews the theme type as 'never'?

can't be serious...

**Comment by efstathiosntonas** [comment]
/rant IntelliJ and Webstorm is getting worse and worse in every single update. The amount of bugs these products have is beyond reality (been using them for 5 years daily), a visit in Youtrack will convince you.

Anyway, can you guys try this out and check if typings are still wrong? 

* https://blog.jetbrains.com/webstorm/2023/12/try-the-future-typescript-engine-with-the-webstorm-next-program/
