### ISSUE TITLE
Wrong styles type provided by useStyles which has stylesheet with Platfrom.select(...)

### ISSUE THREAD

**Issue by sapkotamadhusudan** [jpudysz/react-native-unistyles#130]
### Description

The platform-specific style property gets defaulted to `ColorValue` when we use `Platform.select({ android: {...}, ios: {...}, ... })` inside stylesheet.

### Steps to reproduce

1. Create stylesheet using Platform API

```
const stylesheet = createStyleSheet({
  toastContainer: {
    opacity: 1,
    minHeight: 60,
    ...Platform.select({
      ios: {
        shadowRadius: 12,
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 1 },
        shadowColor: "black",
      },
      android: {
        elevation: 1,
      },
      default: {},
    }),
  },
});
```
2. Use the styles in any `View` component
```
const { styles, theme } = useStyles(stylesheet);

<View style={styles.toastContainer} />
```

3. All the later platform styles type will be defaulted to `ColorValue`, here `elevation` type is defaulted to `ColorValue`.

![Screenshot 2024-01-18 at 2 33 16 PM](https://github.com/jpudysz/react-native-unistyles/assets/20489827/913ae2b2-42b6-4c8c-8ada-f1d10d4eb7cd)
![Screenshot 2024-01-18 at 2 33 44 PM](https://github.com/jpudysz/react-native-unistyles/assets/20489827/536aa227-0225-4927-bbff-c52bf7bbb481)

### Unistyles version

2.0.0

### React Native version

0.73.2

### Platforms

Android, iOS, React Native Web

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Thank you for the report. I know where the issue is, it's about Unistyles TypeScript types.

I will patch it as soon as possible, but it will most likely be next week due to my vacation.

**Comment by jpudysz** [comment]
What's your TypeScript version? I'm getting different results running your example:

<img width="642" alt="Screenshot 2024-01-23 at 05 05 48" src="https://github.com/jpudysz/react-native-unistyles/assets/9088288/add4da44-9a18-453b-8cd3-ac414ae9533b">

Type:
```
(property) toastContainer: {
    shadowRadius: number;
    shadowOpacity: number;
    shadowOffset: {
        width: number;
        height: number;
    };
    shadowColor: string;
    elevation?: undefined;
    opacity: number;
    minHeight: number;
} | {
    elevation: number;
    ... 5 more ...;
    minHeight: number;
} | {
    ...;
}
```

I'm running your example in Unistyles `example` folder with Unistyles 2.0.2 and TS version set to 5.3.3

**Comment by sapkotamadhusudan** [comment]
@jpudysz I'm not sure if it's my project specific, currently, I'm also using the h Unistyles 2.0.2 and TS version set to 5.3.3.
Here are the dependencies that I'm currently using. 

![Screenshot 2024-01-23 at 10 00 09 PM](https://github.com/jpudysz/react-native-unistyles/assets/20489827/d77736d4-99cc-4a96-bd9f-b559f3561920)

**Comment by jpudysz** [comment]
Oh, thanks for the edit!
To be honest, I don't know why you have a different output. It should be exactly the same for everyone.

I will be waiting for your reply about this issue as I'm intrigued 🤔

**Comment by sapkotamadhusudan** [comment]
@jpudysz Finally! After comparing every part with the new project, able to solve the issue. Not sure why it was caused.
I did added the compilerOptions i.e `"strict": true,` in `tsconfig.json` ✨ its working.

**Comment by jpudysz** [comment]
Thanks for the hint! 

If someone will encounter it again I will mention it in the docs 💪
