### ISSUE TITLE
Can not be downloaded from yarn registry

### ISSUE THREAD

**Issue by ramazanguclu** [jpudysz/react-native-unistyles#146]
### Description

 I tried to install the library with this command **yarn add react-native-unistyles** but i got error like 
_An unexpected error occurred: "https://registry.yarnpkg.com/react-native-unstyles: Not found"._

Please help me.

### Steps to reproduce

1.  Run this command **yarn add react-native-unistyles**
2.  Getting not found error

### Unistyles version

2.2.0

### React Native version

0.72.6

### Platforms

Android, iOS, React Native macOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
You didn't spell corectly `unistyles`:

`https://registry.yarnpkg.com/react-native-unstyles`, but should be `https://registry.yarnpkg.com/react-native-unistyles`
