### ISSUE TITLE
[android] Throwing new exception

### ISSUE THREAD

**Issue by willerrodrigo** [jpudysz/react-native-unistyles#153]
### Description

Hello, I'm receiving this error after building (expo dev client - sdk 50) and launching the app.

Edit: using version 2.3.0 it works.

```
thread.cc:2372] Throwing new exception 'no "I" field "height" in class "Lcom/unistyles/Dimensions;" or its superclasses' with unexpected pending exception: java.lang.NoSuchFieldError: no "I" field "width" in class "Lcom/unistyles/Dimensions;" or its superclasses
thread.cc:2372]   at void com.unistyles.UnistylesModule.nativeInstall(long, com.unistyles.Dimensions, java.lang.String, java.lang.String, com.unistyles.Insets, com.unistyles.Dimensions, com.unistyles.Dimensions) (SourceFile:-2)
thread.cc:2372]   at boolean com.unistyles.UnistylesModule.install() (SourceFile:-1)
thread.cc:2372]   at void com.facebook.jni.NativeRunnable.run() (SourceFile:-2)
thread.cc:2372]   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:938)
thread.cc:2372]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
thread.cc:2372]   at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (SourceFile:-1)
thread.cc:2372]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:201)
thread.cc:2372]   at void android.os.Looper.loop() (Looper.java:288)
thread.cc:2372]   at void com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run() (SourceFile:-1)
thread.cc:2372]   at void java.lang.Thread.run() (Thread.java:920)
thread.cc:2372] 
```

### Steps to reproduce

1. Build app with expo dev client
2. Launch the app

### Unistyles version

^2.4.0

### React Native version

0.73.4

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey! 
Did you forget to run `yarn expo prebuild --clean`?
A lot has changed on native side, and you need to generate a new build.

Tested today on fresh project.

**Comment by jpudysz** [comment]
Can you check one more time?

**Comment by willerrodrigo** [comment]
Yes, I tried many times, so weird...

**Comment by jpudysz** [comment]
Can you give me a repo with repro?

**Comment by jpudysz** [comment]
Okay, I can confirm the issue. The problem arises from using ProGuard.

ProGuard modifies the names of the height and width fields in the Dimensions class, which JNI accesses. It's crucial to maintain their original names, as C++ expects to find height and width.

I will attempt to prepare the rule and add it to the documentation.

**Comment by willerrodrigo** [comment]
Cool! I'll be waiting.

Thank you.

**Comment by jpudysz** [comment]
Done, works as intended with proguard:

![image](https://github.com/jpudysz/react-native-unistyles/assets/9088288/b09d96d7-d3f0-4242-9fa0-19e07c608bd2)

Here is the section in the docs:  https://www.unistyl.es/reference/faq/#my-release-app-is-crashing-on-startup-android-with-proguard-enabled

And solution for you:

```diff
"android": {
  "enableProguardInReleaseBuilds": true,
- "extraProguardRules": "-keep public class com.horcrux.svg.** {*;}",
+ "extraProguardRules": "-keep public class com.horcrux.svg.** {*;} -keep class com.unistyles.** { *; }",
  "allowBackup": false
}
```

Thank you for the report and repo with reproduction 🙏
