### ISSUE TITLE
beta.5

### ISSUE THREAD

**Issue by jpudysz** [jpudysz/react-native-unistyles#16]
- [x] support empty objects as valid styles
- [x] transform depracated styles to CSS counterparts (web): https://github.com/necolas/react-native-web/releases
- [x] support text shadow
- [x] improve unistyles <> react-native-web interop 
- [x] add better types for media queries instead of generic `string`

**Comment by atanaskanchev** [comment]
FYI there's no performance regression in beta 4, it's still 🥇 

<img width="500" height="700" src="https://github.com/jpudysz/react-native-unistyles/assets/4958587/2f745fbd-61d7-4aec-870e-f09e9e50c79a">
<img width="500" height="700" src="https://github.com/jpudysz/react-native-unistyles/assets/4958587/59942ddc-1227-42f3-a482-2319795a64b2">

**Comment by atanaskanchev** [comment]
Yes, it's kind of random deviation on each run, sometimes they actually swap places. I wonder if the fact that the test is written in pure js could mask some performance issues in ts.

**Comment by khagesh** [comment]
Any idea on how we can add support for css variables in unistyles?

**Comment by jpudysz** [comment]
Can you describe your idea?

**Comment by jpudysz** [comment]
I've just published beta.5 to npm 🎊

**Comment by claudesortwell** [comment]
> Any idea on how we can add support for css variables in unistyles?

@khagesh They should already be supported just have a theme.web.js file and instead of the color hex just do the css variable. You'll have to have an override index.html to inject the css values.

**Comment by khagesh** [comment]
Hmm, but the css variables can't be string. Can you share an example of what would you write in theme.web.js.

**Comment by jpudysz** [comment]
Instead, could you provide an overall example of how it should work? Maybe it’s easy to add this addition to the core 🤞
