### ISSUE TITLE
Unistyles runtime is not available. Make sure you followed the installation instructions

### ISSUE THREAD

**Issue by gulsher7** [jpudysz/react-native-unistyles#160]
### Description

Hello team, I encountered an error while testing my component with Jest. It seems like there might be an issue with my configuration, but I'm having trouble resolving it. Could you please take a look?

<img width="953" alt="Screenshot 2024-03-10 at 5 00 40 PM" src="https://github.com/jpudysz/react-native-unistyles/assets/56266123/1f63eae7-20ad-42fe-b629-04865cc3d3e5">

### Steps to reproduce

1. Go to project root directory 
2. run script -->>> npm run test

### Snack or a link to a repository (optional)

https://github.com/CodeBrewLabs7/BrewRNKit/tree/unistyle/template

### Unistyles version

2.4.0

### React Native version

0.73.5

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey 👋 please update to 2.5.0-rc0 where I introduced first class mock support. Here are more details: https://github.com/jpudysz/react-native-unistyles/discussions/88#discussioncomment-8731989

https://reactnativeunistyles.vercel.app/reference/testing/

**Comment by gulsher7** [comment]
just checked now i'm getting this error 

```javascript
      Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
 ```

<img width="953" alt="Screenshot 2024-03-10 at 5 00 40 PM" src="https://github.com/jpudysz/react-native-unistyles/assets/56266123/11a0b96d-66d8-45e3-b59a-b37a301a3742">

**Comment by gulsher7** [comment]
updated the above screenshot**

**Comment by jpudysz** [comment]
Please read the documentation, I've provided. The answer is there

**Comment by gulsher7** [comment]
> Please read the documentation, I've provided. The answer is there

resolved thanks for quick response.
