### ISSUE TITLE
UnistylesRegistry breaks test with barrel files

### ISSUE THREAD

**Issue by rokkoo** [jpudysz/react-native-unistyles#194]
### Description

Hello @jpudysz! 👋 I'm adding the Unistyles library to my project. This project has a lot of tests. I have splited the project into multiple folders that use barrel files. When I add the `UnistylesRegistry` to the Jest config, all the tests that use those barrel files don't pass. In order to fix it, I need to specify the exact path of the import that I need. Without UnistylesRegistry, it works perfectly.

Im using monorepo with a beare react native project.

### Initialise `UnistylesRegistry` on `jest.config.js`.
```js
require('./theme/unistyles');
```

### Unistyles setup
```js
// unistyles.ts
import { UnistylesRegistry } from 'react-native-unistyles';
import { LightTheme } from './themes';
import { breakpoints } from './breakpoints';

// if you defined breakpoints
type AppBreakpoints = typeof breakpoints;

// if you defined themes
type AppThemes = {
  light: typeof LightTheme;
};

// override library types
declare module 'react-native-unistyles' {
  export interface UnistylesBreakpoints extends AppBreakpoints {}
  export interface UnistylesThemes extends AppThemes {}
}

UnistylesRegistry.addThemes({
  light: LightTheme,
})
  .addBreakpoints(breakpoints)
  .addConfig({
    adaptiveThemes: false,
  });

```

### Hook file
```js
// hook.ts

// fails ❌
import { InfoService } from '@repo/universal';

// pass ✅
import * as InfoService from '@repo/universal/services/info-service';
```

### (Jest) Test file
```js
// hook.test.ts
jest.mock('@repo/universal/services/info-service', () => ({
  getVersion: jest.fn(() => Promise.resolve(mockVersion)),
}));
```

### Unistyles version

2.7.1

### React Native version

0.73.5

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
Hey, and what's the issue on Unistyles side?

You have a unique monorepo setup, and I have no control over how Jest resolves the files.

**Comment by vargas-arthur** [comment]
I am having similar problems when adding `UnistylesRegistry` to `jestSetup`.
A lot of my tests starts breaking with very strange behaviors, but the tests go back to normal when I remove it.
It is even changing expected result values from tests, which is very unusual.

I am not sure about why this happens but I couldn't find anything else related to this problem so I am commenting on this closed issue to see if I can get some help.

If you want I can share more context and code details
