### ISSUE TITLE
plugins : autoGuidelinePlugin

### ISSUE THREAD

**Issue by TomWq** [jpudysz/react-native-unistyles#200]
### Description

"I used the autoGuidelinePlugin provided by the author in the example, but I encountered an issue. When I assign a circular shape to a view like this:
avatar: {
   width: 80,
        height: 80,
<img width="486" alt="QQ20240511-152253@2x" src="https://github.com/jpudysz/react-native-unistyles/assets/14167500/b492cceb-1f26-44f8-abd2-6c29ee36222b">

        borderRadius: 40
    backgroundColor: theme.colors.background
},
It displays as a circle on iOS, but on Android, it's a flat pattern. Is this normal?"

### Steps to reproduce

It's all written up there

### Unistyles version

2.7.2

### React Native version

0.73.6

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey, example is an example. Try to understand the plugin code and what's going on with your styles. You can always use debugger or console.log to check the values. 

It seems that one of the dimensions are altered by the plugin. Figure out how to add "if" and isolate the problem. 

It's just a plain JavaScript, for sure you will figure it out.

**Comment by efstathiosntonas** [comment]
in some cases you need `overflow:hidden` when playing with borderRadius on Android
