### ISSUE TITLE
Docs failing

### ISSUE THREAD

**Issue by benprebble-maker** [jpudysz/react-native-unistyles#205]
### Description

Docs are failing due to disabled Vercel deployment:

https://reactnativeunistyles.vercel.app/

### Steps to reproduce

Navigate to [https://reactnativeunistyles.vercel.app/](https://reactnativeunistyles.vercel.app/) to see failed deployment notice.

![Screenshot 2024-05-28 at 1 32 32 PM](https://github.com/jpudysz/react-native-unistyles/assets/67561895/69a75b2e-85d3-4042-8e0a-f673f430913e)

### Snack or a link to a repository (optional)

https://reactnativeunistyles.vercel.app/

### Unistyles version

N/A

### React Native version

N/A

### Platforms

Android, iOS, React Native Web, SSR, React Native macOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
Haha, I forget to pay. Should work now!
