### ISSUE TITLE
Breakpoints don't trigger on iPadOS when resizing a window with Stage Manager

### ISSUE THREAD

**Issue by vanstinator** [jpudysz/react-native-unistyles#208]
### Description

iPadOS provides some primitive window management features through Stage Manager. When resizing a React Native view using Unistyles and breakpoints one would expect that as you make the window smaller your UI will re-render with the correct styling for the given set of breakpoints. Instead the UI stays the same and overflows outside of the bounds of the application window.

I'm happy to put together an example repo if necessary, but this behavior seems trivial to reproduce in any repo that I've tried it in.

Interestingly if I console.log the `Dimensions.width` or `Dimsensions.height` from the `Dimensions` package in `react-native` the values update in realtime as I resize the window. So it seems the RN runtime is detecting the size.

### Steps to reproduce

1. Grab an iPad or an iPad simulator
2. Enable Stage Manager - https://support.apple.com/en-us/105075
3. Install your favorite React Native app that uses Unistyles
4. Change the size of the screen and observe the styles don't update accordingly

### Unistyles version

2.7.2

### React Native version

0.74.1

### Platforms

iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey 👋 thanks for the report. 
Should be easy to do (I guess), and I'm willing to support it as I'm also building cross platform.

Will get back to you, when I will have a plan when to release it.

**Comment by vanstinator** [comment]
I was interesting in learning more about unistyles and wanted to take a stab at this myself. It ended up being fairly simple!

https://github.com/jpudysz/react-native-unistyles/pull/209

**Comment by jpudysz** [comment]
How cool is that ?! Thank you!
I will review and test it. So most likely it will be merged in 1-2 days.

**Comment by vanstinator** [comment]
> How cool is that ?! Thank you!

No problem! Happy to help!
