### ISSUE TITLE
Bugs with typescript

### ISSUE THREAD

**Issue by fciprian42** [jpudysz/react-native-unistyles#228]
### Description

Hello,
I have somes problems with typescript in my IDE as you can see below
<img width="848" alt="Capture d’écran 2024-07-01 à 09 41 44" src="https://github.com/jpudysz/react-native-unistyles/assets/23449593/2556492a-8c0d-40ea-90c3-18cf70ff2b82">
<img width="868" alt="Capture d’écran 2024-07-01 à 09 42 04" src="https://github.com/jpudysz/react-native-unistyles/assets/23449593/157fcd14-4c85-4dfc-bae9-db8afdd6faad">

There is my setup file (that is imported in my code after)

`import { UnistylesRegistry } from "react-native-unistyles";

import { breakpoints } from "./breakpoints";
import { lightTheme, darkTheme } from "./themes";

type AppBreakpoints = typeof breakpoints;
type AppThemes = {
  light: typeof lightTheme;
  dark: typeof darkTheme;
};

declare module "react-native-unistyles" {
  export interface UnistylesBreakpoints extends AppBreakpoints {}
  export interface UnistylesThemes extends AppThemes {}
}

UnistylesRegistry.addBreakpoints(breakpoints)
  .addThemes({
    light: lightTheme,
    dark: darkTheme,
  })
  .addConfig({
    adaptiveThemes: true,
  });`
  
  Is there something I'm missed up?
  Thanks

### Steps to reproduce

I created a new project under Expo ~51.0.16 with the 2.8.1 of unistyles and then I followed the guide

### Unistyles version

2.8.1

### React Native version

0.74.2

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
Hey 👋🏼
That's only about your local setup.

What is your TS version / IDE?

**Comment by fciprian42** [comment]
Hey !
Im using Typescript 5.1.3 and my IDE is IntelliJ IDEA 2023.3.7

**Comment by jpudysz** [comment]
Should work the same like on Webstorm.
TypeScript is a little bit behind, so you can update it to higher version.

Can you also try with other IDE like VS or Webstorm?

**Comment by fciprian42** [comment]
Indeed looks like an IDE problem, with VS it works fine

**Comment by jpudysz** [comment]
Can you try (I'm just guessing as I'm using Webstorm):

Settings > Languages & Frameworks > TypeScript

Disable "use types from server" or try to enable/disable other options.

**Comment by fciprian42** [comment]
Hmm It doesn't work 
Im occurred another problem with the theme and typescript
I apply the initial theme by
`useInitialTheme("light");`

if I'm logging the theme I get
{"colors": {"background": "#ffffff", "test": "red", "typography": "#000000"}, "components": {"typography": {"base": [Object], "bold": [Object], "heading": [Object], "regular": [Object], "thin": [Object]}}, "radius": {"lg": 12, "md": 8, "sm": 4, "xl": 16}, "spaces": {"lg": 8, "md": 4, "sm": 2, "xl": 12}}

but through the `createStyleSheet` theme.components or even theme.colors.test is not available but it work fine it's apply the color red from `test`

**Comment by fciprian42** [comment]
It's like the initial theme taking dark even if I use useInitialTheme to light

**Comment by jpudysz** [comment]
You shouldn't apply `useInitialTheme` with `adaptiveThemes`. It's mentioned in the docs. Please verify that you did setup everything correctly. Also, please check many examples available on the Github as well as other stand-alone repos like https://github.com/jpudysz/react-native-unistyles-expo-router

I also recommend to use VSC or Webstorm.

**Comment by fciprian42** [comment]
Yes i see that on doc but I removed adaptiveThemes (so it's false by default) and put initialTheme to light in the `addConfig` but nothing

(I'm using VS this time)

**Comment by jpudysz** [comment]
>It's like the initial theme taking dark even if I use useInitialTheme to light

You can verify which theme is selected with `UnistylesRuntime.themeName`

Unistyles is injecting the same theme to `createStyleSheet` and useStyles`.
