### ISSUE TITLE
Android platform, in versions 2.8.0+, when the keyboard pops up, the bottom insert is incorrect.

### ISSUE THREAD

**Issue by dppo** [jpudysz/react-native-unistyles#230]
### Description

when the keyboard pops up

miniRuntime.insets.bottom =  
287
but in useSafeAreaInsets
insets.bottom =  
24

### Steps to reproduce

console.log('miniRuntime.insets.bottom = ', miniRuntime.insets.bottom);
console.log('miniRuntime.navigationBar.height = ', miniRuntime.navigationBar.height);

const insets = useSafeAreaInsets();
console.log('insets = ', insets.bottom);

 LOG  11:40:05 AM | DEBUG : miniRuntime.insets.bottom =  
287

 LOG  11:40:05 AM | DEBUG : miniRuntime.navigationBar.height =  
287

 LOG  11:40:05 AM | DEBUG : insets =  
24

### Unistyles version

2.8.0

### React Native version

0.74.3

### Platforms

Android

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
Thanks for the report! I need to ignore the IME insets (keyboard).

**Comment by jpudysz** [comment]
Hmm I can't repro 🤔 

https://github.com/jpudysz/react-native-unistyles/assets/9088288/c259b4ee-8aea-46af-b035-bc86d9b7ffd6

![image](https://github.com/jpudysz/react-native-unistyles/assets/9088288/fe285585-3816-4d9f-af5e-31599ae5adbf)


Can you show me how to repro?

**Comment by dppo** [comment]
> Hmm I can't repro 🤔
> 
>  Screen.Recording.2024-07-04.at.17.21.04.mov 
> ![image](https://private-user-images.githubusercontent.com/9088288/345882710-fe285585-3816-4d9f-af5e-31599ae5adbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDQxMTksIm5iZiI6MTcyMDE0MzgxOSwicGF0aCI6Ii85MDg4Mjg4LzM0NTg4MjcxMC1mZTI4NTU4NS0zODE2LTRkOWYtYWY1ZS0zMTU5OWFlNWFkYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDE0MzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQxMjY5N2Y4ODQ3NTc0MjA3ZGNlNTZiODI5YTRmYzNiYjM0MDhlYzE0ZDlhYjVmMWQ1MzhkOTYzNjViZTlmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o0MrIwl3yRwZKwJOD7qNikTZ1RsaHdQ1X7RNqtI_Sog)
> 
> Can you show me how to repro?

I wrote a reproducible code [this](https://github.com/dppo/Repro_230)

**Comment by mobily** [comment]
hey @jpudysz! 👋 I'm having the same (?) issue. When I hide the keyboard and wait for a few seconds, there's some strange behavior happening. Unistyles is giving new insets values (see timestamps):

```bash
2024-07-05T10:11:00.092Z android insets {"bottom": 16, "left": 0, "right": 0, "top": 34}
2024-07-05T10:11:15.953Z android insets {"bottom": 327, "left": 0, "right": 0, "top": 34}
2024-07-05T10:11:31.128Z android insets {"bottom": 16, "left": 0, "right": 0, "top": 34}
```

**Comment by jpudysz** [comment]
@dppo thank for the repo. I was able to repro it 🙏 

I will create a patch

**Comment by jpudysz** [comment]
https://github.com/jpudysz/react-native-unistyles/assets/9088288/590a6086-3a80-494a-8415-374c49799759

This is with extra patch -> if keyboard is visible then inset is 0. Without it it's little bit uglier:

![image](https://github.com/jpudysz/react-native-unistyles/assets/9088288/d5c81cad-e4d5-49fd-affd-22b5b7d44aa2)

Still wondering if it will break anything.
