### ISSUE TITLE
android:windowSoftInputMode="adjustResize" not working properly with Unistyles

### ISSUE THREAD

**Issue by Ashabu** [jpudysz/react-native-unistyles#241]
### Description

When you try to avoid the keyboard on android and get the same behavior as for ios with config 
```
<KeyboardAvoidingView 
      style={{ flex: 1}}  
       behavior={Platform.select({
             ios: 'padding',
              android: undefined,
        })}>
</KeyboardAvoidingView> 
```
I also use  
`android:windowSoftInputMode="adjustResize" `
in AndroidManifest.xml

![without unistyles ](https://github.com/user-attachments/assets/7bdc36b8-3e6f-4747-a5e7-9bc961ae0361)

After installing unistyles i guess android:windowSoftInputMode="adjustResize this breaks because the keyboard is not avoiding the view and content anymore 

![with unistyles ](https://github.com/user-attachments/assets/9bfc70ec-af01-4fd6-81c4-47d4e760a61e)

I tried different configuration for behavior or android:windowSoftInputMode but none of them fix the issue.
Could you please help me with that? Thanks in advance!

### Steps to reproduce

1. Initiate React native app
2. Install Unistyles 2.8.3
3. Wrap the children in <KeyboardAvoidingView>

### Snack or a link to a repository (optional)

https://snack.expo.dev/NgtgmuKmO1oj1XRjeBgdL

### Unistyles version

2.8.3

### React Native version

0.74

### Platforms

Android

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by VolodymyrKashaniy** [comment]
The same with me.

**Comment by jpudysz** [comment]
I will check it out today. Thanks for the report 🙏🏼

**Comment by jpudysz** [comment]
Have you tried to use `padding` behaviour for Android too?
It works as expected. Default behaviour is different with Unistyles as I'm enabling edge-to-edge layout.

```tsx
 <KeyboardAvoidingView
    style={styles.container}
    behavior="padding"
 >
   <TextInput
      placeholder="Type something"
      style={styles.textInput}
   />
</KeyboardAvoidingView>
```

**Comment by jpudysz** [comment]
You can run the demo in Unistyles `examples`:

https://github.com/jpudysz/react-native-unistyles/blob/main/examples/expo/src/examples/KeyboardScreen.tsx

Let me know if that works for you guys, if so I'll update the docs.

**Comment by jpudysz** [comment]
Thats a great news @Ashabu !
I always appreciate ppl that reports such issues. I'm happy that it works with `padding`.

I will add info to docs later today 🙏🏼
