### ISSUE TITLE
fontScale doesn't update in runtime

### ISSUE THREAD

**Issue by yzhe554** [jpudysz/react-native-unistyles#242]
### Description

UnistylesRuntime.fontScale and runtime.fontScale in createStyleSheet don't update in runtime while contentSizeCategory is updating correctly
<img width="417" alt="image" src="https://github.com/user-attachments/assets/d0938fb9-55d1-43e5-bebf-77dbeaa32915">

### Steps to reproduce

1. Add console.log to any component
```
  console.log('UnistylesRuntime.fontScale: ', UnistylesRuntime.fontScale);
  console.log('UnistylesRuntime.contentSizeCategory: ', UnistylesRuntime.contentSizeCategory);
```
2. change larger accessibility size in simulator

### Unistyles version

2.8.1

### React Native version

0.74.0

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
Tested it on 2.8.3 and I'm receiving updates versions. Can you give me a repo with repro?

**Comment by yzhe554** [comment]
@jpudysz are you using new architecture?

**Comment by jpudysz** [comment]
Yes, I am:

iOS:
![image](https://github.com/user-attachments/assets/5d8bc3e1-718d-4454-a8f8-fce753f49575)

Android:

![image](https://github.com/user-attachments/assets/d87d3faa-9eb8-47a3-9fee-fba4f68a4b35)


```tsx
export const App = () => {
    const { styles } = useStyles(stylesheet)
    console.log(`UnistylesRuntime.contentSizeCategory: ${UnistylesRuntime.contentSizeCategory}`)
    console.log(`UnistylesRuntime.fontScale: ${UnistylesRuntime.fontScale}`)
    
    // other code
    // JSX
}

const stylesheet = createStyleSheet((theme, rt) => {
    console.log(`rt.contentSizeCategory: ${rt.contentSizeCategory}`)
    console.log(`rt.fontScale: ${rt.fontScale}`)
    
    // my styles
}
```

Fell free to reopen with repro. Either you hit an edge case that I'm not aware of, or you're testing it differently.

**Comment by yzhe554** [comment]
@jpudysz I can't replicate this in Expo project, only see this in company's brownfield project.
It's a bit hard to provide a repo.
