### ISSUE TITLE
Changing status bar colour on iOS not working. 

### ISSUE THREAD

**Issue by samducker** [jpudysz/react-native-unistyles#262]
### Description

Changing the status bar colour is not working, I wonder if this is an issue related to theme colours defaults? The behaviour should be that the status bar will change to what I tell it to until I cleanup and set it as undefined.

Hiding the status bar works fine, so I presume my setup is correct. 

I'm using latest version of expo using the react native default api works fine also

```
// react native default api
  useEffect(() => {
    StatusBar.setBarStyle('light-content');
    return () => {
      StatusBar.setBarStyle('default');
    };
  }, []);
  ```

### Steps to reproduce

1. Launch component 
2. Ensure adaptive theme is turned on and you are using both light and dark mode themes and no others
3. Add useEffect with     UnistylesRuntime.statusBar.setColor('red'); or     UnistylesRuntime.statusBar.setColor('#000');

### Unistyles version

2.9.1

### React Native version

0.74.3

### Platforms

iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Please try with 6 digit hex:

https://www.unistyl.es/reference/theming/#system-bars-and-rootview-colors

**Comment by jpudysz** [comment]
Sorry, I didn't think it through. I checked the implementation today, and **iOS doesn't support changing the status bar background color**. What you're referring to is changing the status bar text color. That API is not available in Unistyles. You can use the `StatusBar` module from `react-native`.

Also, `UnistylesRuntime.statusBar.setColor` is marked as Android only: https://www.unistyl.es/reference/theming/#update-statusbar-color-during-runtime

I hope it makes sense now!

**Comment by samducker** [comment]
Thanks for clarification! Apologies for not reading the android only label correctly. Yes using react native option seems to work great for a cross platform solution.
