### ISSUE TITLE
Property 'breakpoints' does not exist 

### ISSUE THREAD

**Issue by jerearaujo03** [jpudysz/react-native-unistyles#267]
### Description

I've updated from `2.8.0-beta.5` to `2.9.1` and cannot access `runtime.breakpoints` anymore.
I don't see any breaking change, and [I can see](https://www.unistyl.es/reference/unistyles-runtime/#:~:text=%2D-,breakpoints,-Object) `breakpoints` as part of Unistyles Runtime and nothing related to this property not being present in the [mini runtime](https://www.unistyl.es/reference/create-stylesheet/#:~:text=Since%20version%202.8.0%2C%20the%20library%20will%20inject%20mini%20runtime%20which%20is%20a%20subset%20of%20the%20original%20UnistylesRuntime%20without%20methods%20like%20setTheme%20or%20setRootViewBackgroundColor%2C%20which%20are%20not%20useful%20when%20defining%20your%20stylesheets.)

### Steps to reproduce

Example working in previous version that doesn't work in 2.9.1:
```tsx
const stylesheet = createStyleSheet((theme, runtime) => ({
  container: { flexDirection: "row", justifyContent: "center" },
  link: { flex: 1, maxWidth: runtime.breakpoints.lg },
  card: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: spacing.sm,
  },
}));
```

### Unistyles version

2.9.1

### React Native version

0.75.1

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey 👋 

I can confirm that miniRuntime doesn't expose breakpoints. It exposes only the current breakpoint. 

This prop was not removed, I just didn't forward it. Anyway, I don't see a problem of doing so. 

Thanks for pointing this out. I will release new version tomorrow.

**Comment by jerearaujo03** [comment]
I changed my code to use breakpoints from my breakpoints file directly.
I'm not sure if exposing breakpoints in the runtime makes sense because I can do something like this, and I can avoid passing a function to `createStyleSheet` (if I'm using runtime only to get breakpoints, like in my case)

```diff
import { breakpoints } from "@/theme';

--const stylesheet = createStyleSheet((theme, runtime) => ({
++const stylesheet = createStylesSheet({
  ...
  link: { flex: 1, maxWidth: breakpoints.lg },
  ...
--}));
++});
```

**Comment by jpudysz** [comment]
That's true! I also removed it from 3.0 with the same argument in mind. 

If that's also fine for you then we can close this issue.
