### ISSUE TITLE
rerender Issue with useStyle and react-native-keyboard-controller Combination

### ISSUE THREAD

**Issue by sssajjad007** [jpudysz/react-native-unistyles#275]
### Description

Hi, I've encountered a problem and hope you can help me.

When I use useStyle and react-native-keyboard-controller together, every time I open and close the keyboard, it causes a rerender. But when I use useStyle alone, as long as I add disableAnimatedInsets: true, rerendering doesn't happen.

If I remove useStyle and use StyleSheet.create along with keyboard-controller, rerendering doesn't happen either.
I tested on Android 14

### Steps to reproduce

1. yarn add react-native-keyboard-controller react-native-reanimated
2. wrap your app with KeyboardProvider component.
3. Use useStyle in a component.
4. Open and close the keyboard multiple times.
5. Observe the component rerendering.

### Snack or a link to a repository (optional)

https://github.com/sssajjad007/unistyleIssue

### Unistyles version

2.9.2

### React Native version

0.75.2

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by MohammadAzimi** [comment]
I've encountered the same issue on my **Android 8.0** device (HUAWEI P10 Lite)
But the behavior is a little bit different on it.

When I wrap the `KeyboardProvider`, an extra rerender happens only once. Once I remove the `KeyboardProvider` only one extra rerender happens when the keyboard gets open. 

Hope this information helps you too

**Comment by sssajjad007** [comment]
Hi,
Any chance we'll get this in v2?

**Comment by jpudysz** [comment]
Hey, I'm focusing now on 3.x branch. 
Nevertheless I promised monthly updates, and for sure I will cook new release this month with support for RN 0.76.
I will then take a look 🙏🏼

**Comment by avega99** [comment]
I am experiencing the same issue in the new Architecture too
