### ISSUE TITLE
Inferred Typescript types don't seem to work well with variants

### ISSUE THREAD

**Issue by slvvn** [jpudysz/react-native-unistyles#279]
### Description

Hi, I seem to have an issue with the types inferred by Unistyles.

### Steps to reproduce

For example, I have this code which I got from the example in the Unistyles repo, and I modified it a bit match my situation.
It has 1 variant (`type`), which is used 2 times (for the `button` style and the `buttonText` style).
```tsx
/* eslint-disable no-restricted-imports */
/* eslint-disable import/no-unused-modules */
import React from "react";
import { Pressable, Text, View } from "react-native";
import { createStyleSheet, useStyles } from "react-native-unistyles";

enum ButtonType {
  Primary = "primary",
  Secondary = "secondary",
}

const stylesheet = createStyleSheet((theme) => ({
  button: {
    borderWidth: 1,
    variants: {
      type: {
        primary: {
          backgroundColor: theme.colors.backgroundButtonPrimary,
        },
        secondary: {
          backgroundColor: theme.colors.backgroundButtonSecondary,
        },
      },
    },
  },
  buttonText: {
    fontWeight: "bold",
    variants: {
      type: {
        primary: {
          color: theme.colors.foregroundButtonPrimary,
        },
        secondary: {
          color: theme.colors.foregroundButtonSecondary,
        },
      },
    },
  },
}));

export const VariantsScreen: React.FC<{
  type: ButtonType;
}> = ({ type }) => {
  const { styles } = useStyles(stylesheet, {
    type,
  });

  return (
    <View>
      <Pressable
        accessibilityRole="button"
        style={styles.button}
        onPress={() => {}}
      >
        <Text style={styles.buttonText}>Change variant</Text>
      </Pressable>
    </View>
  );
};
```

I would expect TS to show me something like this as the type of the styles:
```ts
{
    button: {
        backgroundColor: string
    } & {
        borderWidth: number;
    };
    buttonText: {
        color: string;
    } & {
        fontWeight: "bold";
    };
}
```

However this is the type I'm getting (the style keys inside all the variants are missing):
![Screenshot 2024-09-03 at 16 38 57](https://github.com/user-attachments/assets/427b8b5e-1b02-4c4f-a90f-8067c1ac465e)

Looks like it has something to do with the theme, because when putting the colors directly inline it seems to work:
![Screenshot 2024-09-03 at 16 40 50](https://github.com/user-attachments/assets/ab412c01-1ff4-4abd-bdb1-5b879ebe36ce)

I noticed that the types are correctly inferred when removing the `secondary` type from both variants (which leaves me with just the `primary` type):
![Screenshot 2024-09-03 at 16 42 26](https://github.com/user-attachments/assets/d01b09aa-8626-4fbb-b6f9-c293a3c9b1ff)

### Unistyles version

2.9.2

### React Native version

0.73.6

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Thank you for the report. I will try to repro it and let you know

**Comment by jpudysz** [comment]
Tested it in Unistyles repo. I can't reproduce it.

My tests:

1. Create component with your styles (I use my own colors):
```tsx
const stylesheet = createStyleSheet(theme => ({
    container: {
        borderWidth: 1,
        variants: {
            type: {
                primary: {
                    backgroundColor: theme.colors.accent
                },
                secondary: {
                    backgroundColor: theme.colors.aloes
                }
            }
        }
    },
    text: {
        fontWeight: 'bold',
        variants: {
            type: {
                primary: {
                    color: theme.colors.typography
                },
                secondary: {
                    color: theme.colors.fog
                }
            }
        }
    }
}))
```

2. Create component with variants:

```tsx
enum ButtonType {
    Primary = 'primary',
    Secondary = 'secondary',
}

type ExampleScreenProps = {
    type: ButtonType
}

export const ExampleScreen: React.FunctionComponent<ExampleScreenProps> = ({ type }) => {
    const { styles, theme } = useStyles(stylesheet, {
        type
    })
    
    // ...
}
```

Result:

<img width="362" alt="image" src="https://github.com/user-attachments/assets/f7c09e79-770b-40ed-8d5b-dfdd9267f68e">

How themes are defined:

https://github.com/jpudysz/react-native-unistyles/blob/main/examples/expo/src/styles/theme.ts

Make sure that each theme has the same type.
