### ISSUE TITLE
Is this the way to get the InelliSense for styling?

### ISSUE THREAD

**Issue by Albert-Gao** [jpudysz/react-native-unistyles#28]
Hi, I noticed that when writing the styles, there is no IntelliSense for the sub-object, I use the `as` hack to workaround it, is it the suggested way or i am missing something? Thanks :)

**
<img width="454" alt="image" src="https://github.com/jpudysz/react-native-unistyles/assets/18282328/8eb05382-f5c4-424d-a6ec-f605cbf0065d">
**

**Comment by jpudysz** [comment]
Can you confirm that you are running version 1.0.0-rc.1? 

In some older beta versions, there was an issue with TS hints in nested objects.

**Comment by Albert-Gao** [comment]
yes, i am using rc1, prior rc1, this `as` cast causes a type error, it is solved after upgrading to rc1, but still no IntelliSense if no `as`

<img width="311" alt="image" src="https://github.com/jpudysz/react-native-unistyles/assets/18282328/9b20e071-da6f-47c5-9e8c-51e4744eff43">

**Comment by jpudysz** [comment]
Can you check the `examples` folder and reproduce it? I can see IntelliSense everywhere:

Breakpoints:

<img width="587" alt="breakpoint" src="https://github.com/jpudysz/react-native-unistyles/assets/9088288/e5f0c0f3-6e73-4044-a879-b0881350d74a">

Objects with theme:

<img width="587" alt="object" src="https://github.com/jpudysz/react-native-unistyles/assets/9088288/ec159eb5-df98-4bdf-8483-3445301ce087">

Objects without theme:

<img width="723" alt="image" src="https://github.com/jpudysz/react-native-unistyles/assets/9088288/8442d945-fdd1-4be6-8070-6f879674fe19">

**Comment by Albert-Gao** [comment]
Thanks mate, I know the problem, once updated to rc1, the createStyles changed to createStyleSheet, now all works :D

**Comment by jpudysz** [comment]
No problem 🙏

Let me know if you encounter any other issues
