### ISSUE TITLE
Android inset differs between devices

### ISSUE THREAD

**Issue by jordmccord** [jpudysz/react-native-unistyles#291]
### Description

I've implemented the recommended inset fix on android but I'm seeing different results on multiple devices. Is this the expected behaviour? If so how do I make sure it's the same on all Android devices?

*Moto e13 with correct inset*
![Screenshot_20240917-141342](https://github.com/user-attachments/assets/03b83a4a-551e-41d6-b51a-c93fe17f9b5c)

*Samsung S10e with much larger inset*
![image (1)](https://github.com/user-attachments/assets/2c518309-5743-4c0b-ab96-f42ec51260a3)

### Steps to reproduce

1. Implement edge to edge styles fix https://www.unistyl.es/reference/edge-to-edge/
2. Test on multiple Android devices and see different results

### Unistyles version

2.9.2

### React Native version

0.74.5

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jordmccord** [comment]
Fixed the issue by using `useSafeAreaInsets` from `'react-native-safe-area-context'`. The issue corrected itself when app went into the background using `react-native-unistyles` if this info helps?

**Comment by jpudysz** [comment]
Yeah, it seems that other library is modifying edge-to-edge layout. Unistyles automatically enables (forces) edge to edge while coming from background to foreground.

Please check the list of libs and how to force e2e with them: 
https://www.unistyl.es/reference/faq/#my-android-app-is-not-edgetoedge-or-insets-are-incorrect

**Comment by a-eid** [comment]
@jpudysz are there any libraries that you would advice against using with unistyles ?

**Comment by jpudysz** [comment]
I prepared a list in the link above. You need to make sure to enable settings mentioned in the FAQ.
