### ISSUE TITLE
Color Themes

### ISSUE THREAD

**Issue by claudesortwell** [jpudysz/react-native-unistyles#3]
Whats the best way to do color themes like darkmode and lightmode?

Current way from the docs I can think is switching the whole theme thats passed into the provider.

If there is currently no best way, im happy to do a PR with examples (+ any code if needed).

**Comment by jpudysz** [comment]
Hey @claudesortwell, thanks for the question.

For a more detailed context, please refer to my blog post where I discussed switching states:
https://www.reactnativecrossroads.com/posts/level-up-react-native-styles#theming-component-variants-and-color-palette

There's an example about dark mode.

I agree that the documentation isn't perfect. I put it together quickly yesterday, and I plan to improve it when I have some free time.

I'm open to PRs 🤗!
