### ISSUE TITLE
KeyboardAvoidingView does not work correctly on Android

### ISSUE THREAD

**Issue by Brma1048** [jpudysz/react-native-unistyles#314]
### Description

After updating `react-native-unistyles` from version `2.7.2` to `2.10.0`, I observed that the `KeyboardAvoidingView` component from `react-native` no longer functions properly. 
Additionally, within my app's chat screen where I use the `KeyboardAccessoryView` from `react-native-keyboard-accessory`, there is now a noticeable delay before the TextInput is elevated above the keyboard after the upgrade. Typing in a TextInput also experiences significant lag. 
Overall, I believe the performance of my Android app has deteriorated following the upgrade.

### Steps to reproduce

Wrap some components inside the `KeyboardAvoidingView`

### Unistyles version

2.10.0

### React Native version

0.75.4

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by Brma1048** [comment]
@efstathiosntonas The problem still exists with the `KeyboardAvoidingView` but the performance is now much better. The `KeyboardAccessoryView` no also works again but i must also removed the `androidAdjustResize` prop.
Do you know when it's useful to set `disableAnimatedInsets` to `true`?

**Comment by justblender** [comment]
>@justblender can you try disabling animated insets?

I can, but I don't think I have any issues with Unistyles at this moment 😜

**Comment by jpudysz** [comment]
@Brma1048 please go through release notes: https://github.com/jpudysz/react-native-unistyles/releases/tag/v2.10.0

**Comment by Brma1048** [comment]
@jpudysz  Please reopen the issue. The `KeyboardAvoidingView` from `react-native` still not works, even if i disableAnimatedInsets.

**Comment by jpudysz** [comment]
I  meant go through release notes from 2.7.2 to 2.10.0. A lot has changed eg. edge to edge layout enabled by default.
If you won't find a solution then please create a repro so I will be able to debug it or help you.

**Comment by Brma1048** [comment]
@jpudysz Found the issue, i had set the `KeyboardAvoidingView` behavior for android to undefined.
As expo team also says that for example in this video:

<img width="983" alt="image" src="https://github.com/user-attachments/assets/22c3a47d-a9cd-4367-960f-7e95cc077364">



but i found in the FAQ your suggestion

<img width="760" alt="image" src="https://github.com/user-attachments/assets/1876c6f9-947e-43f9-8adb-bcb6fd8f82de">

and now it works, thank you :)
