### ISSUE TITLE
Incompatible with expo EAS due to node version

### ISSUE THREAD

**Issue by hannojg** [jpudysz/react-native-unistyles#322]
### Description

Can't use unistyles right now with expo EAS, as they only support node 18. Is there a real reason why the node engine is enforced to 20 in unistyles?

![Screenshot 2024-10-26 at 00 06 34](https://github.com/user-attachments/assets/1d285ad7-dc92-4902-80bc-71a8c3fbe7e1)

### Steps to reproduce

- Create an expo app
- Try to build using eas 

### Unistyles version

2.10.0

### React Native version

0.75.4

### Platforms

Android, iOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
Hey 👋 

There is no real reason. I'm just following Node release cycles:

![image](https://github.com/user-attachments/assets/1c1dcfdb-c021-453e-ae99-d58320796e15)

Node 18 has not been active for a year. I didn’t know EAS was still using it 🤯

I want to release today new version, so I will move it back to Node 18.

**Comment by hannojg** [comment]
Thanks!

**Comment by hercom-app** [comment]
@jpudysz the same problem is happening now with version 3.0.0-beta.1
![{D9A62D32-EFC2-4271-8BF8-E6C77BB4524F}](https://github.com/user-attachments/assets/958dc9e9-63f8-4d0b-91e7-3cdd957ef195)

**Comment by jpudysz** [comment]
Ah thanks for pinging me @Mark-Pineda-C 

I've updated it on 2.x branch only. 
Will add it to beta.2.
