### ISSUE TITLE
Android loses Selected Theme when App is in Background

### ISSUE THREAD

**Issue by kdfemi** [jpudysz/react-native-unistyles#327]
### Description

I created a Dark and Light theme, if I briefly minimize and bring the App back to focus Unistyles loses the  Selected theme unless I close the App and reopen it or I listen to when the App is active and set the initial theme again. This only happens in the Android Production build It works well in Dev and on iOS.

I use Expo 50.0.20

### Steps to reproduce

1. Create a Dark and Light theme on Android
2. set initial theme 
3. Minimize the App and  Bring the App back to focus
4. Check the current set Theme

### Unistyles version

2.10.0

### React Native version

0.73.6

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey, thanks for the report? Can you provide a minimal reproduction?

**Comment by a-eid** [comment]
@jpudysz it's not consistent, this is related to an issue I raised on discord but was not able to reproduce.

**Comment by jpudysz** [comment]
Got it, but without repro I won't be able to help 😥

**Comment by a-eid** [comment]
I understand, as soon as I am able to consistently reproduce it, I will provide a repro.

**Comment by jpudysz** [comment]
Hey @kdfemi I need to close it due to no response & repro. Feel free to reopen with more details.
