### ISSUE TITLE
Duplicate libreactnative.so

### ISSUE THREAD

**Issue by TomAtterton** [jpudysz/react-native-unistyles#330]
### Description

So on android I am using expo@next and tested unistyles with new architecture enabled and it was working fine, but noticed some other bugs unrelated to library so downgraded. Once i downgrade i kept running into the same issue over and over again. Regardless of removing or clearing cache.

`Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libreactnative.so' from inputs:
      - /Users/tom/Projects/advent-app/node_modules/react-native-unistyles/android/build/intermediates/library_jni/debug/copyDebugJniLibsProjectOnly/jni/arm64-v8a/libreactnative.so
      - /Users/tomatterton/.gradle/caches/8.10.2/transforms/80121a83b5798be0b8f8fa5233c29f88/transformed/react-android-0.76.1-debug/jni/arm64-v8a/libreactnative.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets`
     
     
     I found a solution but still thought i should raise this 
     
     `packagingOptions {
        jniLibs {
            useLegacyPackaging (findProperty('expo.useLegacyPackaging')?.toBoolean() ?: false)
            pickFirsts += ['**/libreactnative.so']
        }
    }`
     

### Steps to reproduce

1. install expo@next on your project
2. don't enable new architecture

### Unistyles version

2.11.0

### React Native version

0.76.1

### Platforms

Android

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Hey, thanks for the report. For now let's wait for the stable expo release.

`libreactnative.so` was introduced in 0.76.0 and Unistyles supports it. If you can repro it in bare then it's a real issue.

**Comment by jpudysz** [comment]
I'm gonna fix it in the next patch release

**Comment by dhruvpvx** [comment]
I'm also facing this issue
is there any workaround?

**Comment by TomAtterton** [comment]
> I'm also facing this issue is there any workaround?

@dhruvpvx  I posted a workaround above you need to add this line 

` pickFirsts += ['**/libreactnative.so'] `

inside your app/build.gradle

**Comment by dhruvpvx** [comment]
@TomAtterton 
do I need to add this in app.json file

**Comment by dhruvpvx** [comment]
okay got it,
added in the "packagingOptions"

**Comment by TomAtterton** [comment]
> okay got it, added in the "packagingOptions"

Didn't realise you could just add it actually in the app.json not sure if this is what you meant. Then just run prebuild. 


`      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 35,
            "targetSdkVersion": 35,
            "minSdkVersion": 24,
            "buildToolsVersion": "35.0.0",
            "newArchEnabled": false,
            "packagingOptions": {
              "pickFirst": [
                "**/libreactnative.so"
              ]
            }
          },
          "ios": {
            "deploymentTarget": "15.1",
            "newArchEnabled": false
          }
        }
      ],`

**Comment by a-eid** [comment]
@jpudysz sdk 52 is now stable & issue still reproducible.
