### ISSUE TITLE
Multiple renders on theme change due to useStyles setState

### ISSUE THREAD

**Issue by rams23** [jpudysz/react-native-unistyles#333]
### Description

I have performance issues on switching the theme from dark to light inside my small app. I investigated a bit recreating a minimal repo with expo 51 and unistyles 2.11. The profiler result looks like this when pressing the "change theme" button
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/e0597c87-a825-4b72-b207-8f11cec26033">

I deep-dived into the codebase and saw that the hook `useStyles` listens to the theme change event from the native part and triggers a `setState`. This happens **for every instance of** `useStyles`. We created a temporary patch in our repo changing useStyles to use a context for theme and layout, and register to the change only in a root provider. After the patch the theme change profiling looks like this
![telegram-cloud-photo-size-4-5852686028442290441-y](https://github.com/user-attachments/assets/acf7981e-126c-461a-827d-2da6c21316ed)

With the new architecture the performance issue is mitigated by the automatic batching of React 18.

I don't know if there is another reason to listen to the changes specifically on every useStyles usage, if not I can arrange a pull request from the patch 

### Steps to reproduce

Just create

### Unistyles version

2.11.o

### React Native version

0.74.0

### Platforms

Android, iOS, React Native Web

### Engine

Hermes

### Architecture

Paper (old)

**Comment by rams23** [comment]
I looked into issue and pull request but not in discussion, sorry. Here is a reference #240

**Comment by jpudysz** [comment]
I'm happy to accept PR! 
It just can't change anything apart from internals, otherwise it will be a breaking change. 

Unistyles 3.0 is not using any hooks at all, thus it would be cool to improve 2.x before sunsetting it.
