### ISSUE TITLE
Custom themes getting overridden by adaptive themes on app background / modal screen

### ISSUE THREAD

**Issue by alizahid** [jpudysz/react-native-unistyles#339]
### Description

Hello,

I'm using adaptive themes and custom themes that the users can select. But every time the app goes into background or a screen with `presentation: 'modal'` opens, the theme switches back to adaptive.

Have a look;

https://github.com/user-attachments/assets/77e73ad3-f2b7-4f46-b69f-0ef77f8b5ddc

My themes are defined here https://github.com/alizahid/acorn/blob/main/apps/mobile/src/styles/uni.ts
And the custom theme is set here https://github.com/alizahid/acorn/blob/main/apps/mobile/src/app/_layout.tsx#L27

I wanted to use [`useInitialTheme`](https://reactnativeunistyles.vercel.app/reference/use-initial-theme/) but couldn't figure out how to use it with adaptive themes.

The value of `theme` in `_layout.tsx` never changes unless the user selects a new theme. But the value of `UnistylesRuntime.themeName` changes after background / modal.

Any help would be appreciated, thanks!

### Steps to reproduce

1. Change theme from adaptive to anything else
2. Move app to background / navigate to a modal screen
3. Theme reverts back to adaptive

### Snack or a link to a repository (optional)

https://github.com/alizahid/acorn

### Unistyles version

2.12.0

### React Native version

react-native

### Platforms

iOS

### Engine

Hermes

### Architecture

Fabric (new)

**Comment by jpudysz** [comment]
You need to disable adaptive themes if you want to switch to custom theme. Without it Unistyles will try to force it. 

You can do that with UnistylesRuntime.setAdaptiveThemes(false)

**Comment by alizahid** [comment]
Okay, that actually helps a lot, thanks!

I've changed my `useEffect` such that I default to adaptive themes if no theme is selected, or disable adaptive themes if a theme is selected.

```ts
UnistylesRuntime.setAdaptiveThemes(theme === 'acorn')

if (theme !== 'acorn') {
  UnistylesRuntime.setTheme(theme)
}
```
