### ISSUE TITLE
Plugin Replacement for Dynamic Font Mapping in react-native-unistyles v3?

### ISSUE THREAD

**Issue by bernardogeneroso** [jpudysz/react-native-unistyles#370]
### Description

In version 2 of react-native-unistyles, I used a custom plugin to automatically map the fontWeight property to the corresponding fontFamily. This plugin was essential for dynamically and efficiently managing fonts in my project. However, after migrating to version 3, where plugin support has been removed, I can no longer implement this functionality in the same way.

I would like to know if there is an alternative way to achieve this in version 3, considering the removal of plugin support.
![Screenshot_5](https://github.com/user-attachments/assets/085bbd6b-029b-4080-8ff9-0372d6c00da6)

### Steps to Reproduce

1. In version 2, create a plugin to map fontWeight to fontFamily
2. Apply the plugin in the project and observe that the mapping works automatically.

### Unistyles Version

3.0.0-beta.1

### React Native Version

0.76.3

### Platforms

Android, iOS, Web

### Expo

Yes

**Comment by jpudysz** [comment]
Hey it was asked multiple times already: 

https://github.com/jpudysz/react-native-unistyles/discussions?discussions_q=plugin

Here is more details: https://github.com/jpudysz/react-native-unistyles/discussions/361

Long story short, right now there is no replacement. Could be in the future (maybe closer to stable release).

I will keep this issue open for transparency.
