### ISSUE TITLE
[V3] Can't build app on EAS with USE_FRAMEWORKS

### ISSUE THREAD

**Issue by rainerllera** [jpudysz/react-native-unistyles#371]
### Description

Heya! I'm migrating from Unistyles 2 to v3 beta.

When building an app on EAS with V3 + NitroModules etc, the build can't complete. 

My app uses `USE_FRAMEWORKS` because [it is required](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks) by `react-native-firebase`, which is a commonly used library. 

First issues were related to `react-native-nitro-modules`, which has had a couple of related issues (see [218](https://github.com/mrousavy/nitro/issues/218) and [219](https://github.com/mrousavy/nitro/issues/219)).

Here's an example of the nitro errors I was getting: 

```
❌  (ios/Pods/RCT-Folly/folly/portability/Config.h:20:10)

  18 | 
  19 | #ifndef FOLLY_NO_CONFIG
> 20 | #include <folly/folly-config.h>
     |          ^ 'folly/folly-config.h' file not found
  21 | #endif
  22 | 
  23 | #if __has_include(<features.h>)


❌  (node_modules/react-native-nitro-modules/cpp/core/ArrayBuffer.hpp:11:10)

   9 | 
  10 | #include "OwningReference.hpp"
> 11 | #include <jsi/jsi.h>
     |          ^ could not build module 'jsi'
  12 | #include <thread>
  13 | 
  14 | namespace margelo::nitro {
...
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	EmitSwiftModule normal arm64 (in target 'NitroModules' from project 'Pods')
▸ 	SwiftEmitModule normal arm64 Emitting\ module\ for\ NitroModules (in target 'NitroModules' from project 'Pods')
...
▸ (3 failures)
** ARCHIVE FAILED **
```
I was able to avoid the errors when compiling the nitro modules pod by using [this patch](https://github.com/mrousavy/nitro/issues/219#issuecomment-2426216238).

After that, similar issues have come, but this time when compiling Unistyles:
```
❌  (node_modules/react-native/React/Base/RCTBridge+Inspector.h:11:9)

   9 | 
  10 | #ifdef __cplusplus
> 11 | #import <jsinspector-modern/ReactCdp.h>
     |         ^ 'jsinspector-modern/ReactCdp.h' file not found
  12 | #endif
  13 | 
  14 | @interface RCTBridge (Inspector)


❌  (node_modules/react-native-unistyles/ios/Unistyles.h:4:9)

  2 | 
  3 | #import "jsi/jsi.h"
> 4 | #import <React/RCTUtils.h>
    |         ^ could not build module 'React'
  5 |
... 
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	EmitSwiftModule normal arm64 (in target 'Unistyles' from project 'Pods')
▸ 	SwiftEmitModule normal arm64 Emitting\ module\ for\ Unistyles (in target 'Unistyles' from project 'Pods')
...
▸ (3 failures)
** ARCHIVE FAILED **
```

After doing some digging, I found out the expo team had some similar issues earlier this year with their `expo-dev-client` and `expo-dev-launcher` packages. I think the way they solved it was to handle resolutions in their podspecs considering whether `USE_FRAMEWORKS` was present or not. Please see [28209](https://github.com/expo/expo/issues/28209), [27414](https://github.com/expo/expo/issues/27414))

They fixed them in [this PR](https://github.com/expo/expo/pull/28702)

I don't really know much about how all of this works, but thought it may be worth having a look. I think a lot of people like me are kinda forced to set: 
```
"expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static",
           
          },
```
in our projects by other libraries, so it would be awesome if unistyles 3/nitro could support this! Unfortunately I don't have access to an apple pc rn so can't debug with a local build. 

Apologies for not providing a minimal repro yet, I haven't reproduced outside of my own app. I'll try to provide a minimal one for it soon. as I suspect that a newly created expo app with just the above configuration ` "useFrameworks": "static"` should trigger the errors.

### Steps to Reproduce

TBD

### Unistyles Version

3.0.0.beta1

### React Native Version

0.76.3

### Platforms

iOS

### Expo

Yes

**Comment by frozencap** [comment]
getting the same error

**Comment by mrousavy** [comment]
@jpudysz i'll fix this in Nitro, dont worry

**Comment by jpudysz** [comment]
Thanks for the report, I'll check what I can do on my side.

**Comment by mrousavy** [comment]
This raises a discussion now; how do we want to fix this.

1. Frameworks are a relict of the past, nowadays we can just use static modules in Swift and it's more performant and easier to link. Why are you using Frameworks? I guess only because of Firebase right? ...
2. For some reason, Folly fails to compile with `USE_FRAMEWORKS`. Not Nitro, but Folly. I don't really think it's Nitro's fault, it seems to be Folly's fault. **Should we fix this in Folly?**
3. The current workaround is to disable folly config (set `FOLLY_NO_CONFIG=1` compiler flag) - I think technically we should manually set this in every Nitro Module's `.podspec`, so also here in Unistyles. I don't think this is something that should necessarily be auto-generated, because it has nothing to do with Nitro or Nitrogen. It's a workaround for Folly.

**Comment by jpudysz** [comment]
Hey @mrousavy Unistyles already includes it:
https://github.com/jpudysz/react-native-unistyles/blob/fcedf8834d4b455ad01db11c24222f7d8b202d68/Unistyles.podspec#L22

As far as I remember I wasn't able to compile Nitro on Android without these flags.

**Comment by jpudysz** [comment]
I'm happy to test this `-Swift.h` thing as soon as you release it 🙏

**Comment by mrousavy** [comment]
Actually it might be something different. 

I think Frameworks just need explicit dependencies to be declared, so adding `spec.depdendency 'React-jsi'` fixes the `#include <jsi/jsi.h>` issue.

This needs to happen for every dependency - afaik Nitro only uses JSI and CallInvoker.

**Comment by mrousavy** [comment]
[react-native's `install_module_dependencies(s)` script](https://github.com/facebook/react-native/blob/88c9a42fca63124560f2d5f8b8644337817ebebe/packages/react-native/scripts/cocoapods/new_architecture.rb#L84-L102) should already add those headers to the Podspec...

**Comment by mrousavy** [comment]
Ah you added different header paths. Maybe we should open a PR to react-native core with those then?

**Comment by mrousavy** [comment]
Also, [the default `folly_config`](https://github.com/facebook/react-native/blob/88c9a42fca63124560f2d5f8b8644337817ebebe/packages/react-native/scripts/cocoapods/helpers.rb#L52) already specifies `FOLLY_NO_CONFIG`, so why do we need to specify that again..?

**Comment by mrousavy** [comment]
nvm apparently the react-native script doesn't apply the folly_config to pods.

**Comment by mrousavy** [comment]
got it.

![image](https://github.com/user-attachments/assets/975f340e-bfab-4508-9de4-8845e5daafec)

**Comment by jpudysz** [comment]
> nvm apparently the react-native script doesn't apply the folly_config to pods.

I've checked Reanimated repo, they also apply all folly flags manually. It means that for sure they're not picked up

**Comment by jpudysz** [comment]
@rainerllera can you check if it works for local EAS?

branch: feature/frameworks

**Comment by jpudysz** [comment]
Oh I see. I will try to build with local EAS, so you won't pay for it 😉

**Comment by jpudysz** [comment]
Damn, I don't have local EAS configured. It would be cool if anyone can test it.

**Comment by ice-cap0** [comment]
at my desk in 20 will give it a shot. y'all are cracked

**Comment by ice-cap0** [comment]
gave `prebuild` a shot before EAS, getting 
```
› Signing   expo-eas-client Pods/EASClient » EASClient.framework
› Compiling expo-constants Pods/EXConstants » EXConstants-dummy.m
› Signing   expo-file-system Pods/ExpoFileSystem » ExpoFileSystem.framework
› Signing   react-native-nitro-modules Pods/NitroModules » NitroModules.framework
› Executing expo-updates Pods/EXUpdates » [CP-User] Generate updates resources for expo-updates
› Preparing expo-updates Pods/EXUpdates » EXUpdates-Info.plist

❌  (node_modules/react-native/React/Base/RCTBridge+Inspector.h:11:9)

   9 | 
  10 | #ifdef __cplusplus
> 11 | #import <jsinspector-modern/ReactCdp.h>
     |         ^ 'jsinspector-modern/ReactCdp.h' file not found
  12 | #endif
  13 | 
  14 | @interface RCTBridge (Inspector)


❌  (node_modules/react-native-unistyles/ios/Unistyles.h:4:9)

  2 | 
  3 | #import "jsi/jsi.h"
> 4 | #import <React/RCTUtils.h>
    |         ^ could not build module 'React'
  5 | 
```
but also bun blocked this untrusted postinstall
```
./node_modules/react-native-unistyles @github:jpudysz/react-native-unistyles#92ee8b4
 » [prepare]: husky && bob build
 ```
 not sure if i have to handle that and prob going off track but i tried installing both anyways and ended up getting
 ```
   ⚙️  react-native-unistyles [1/1] .git can't be found✖ No configuration found. Run '../.bin/bob init' to create one automatically.
```
EAS build currently running

**Comment by ice-cap0** [comment]
EAS 
```js
[RUN_FASTLANE] 
⚠️  (ios/build/generated/ios/NitroModulesSpec/NitroModulesSpec.h:44:62)

  42 | facebook::react::EventEmitterCallback _eventEmitterCallback;
  43 | }
> 44 | - (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;
     |                                                              ^ pointer is missing a nullability type specifier [-Wnullability-completeness]
  45 | 
  46 | 
  47 | @end

[RUN_FASTLANE] 
❌  (node_modules/react-native/React/Base/RCTBridge+Inspector.h:11:9)

   9 | 
  10 | #ifdef __cplusplus
> 11 | #import <jsinspector-modern/ReactCdp.h>
     |         ^ 'jsinspector-modern/ReactCdp.h' file not found
  12 | #endif
  13 | 
  14 | @interface RCTBridge (Inspector)

[RUN_FASTLANE] 
❌  (node_modules/react-native-unistyles/ios/Unistyles.h:4:9)

  2 | 
  3 | #import "jsi/jsi.h"
> 4 | #import <React/RCTUtils.h>
    |         ^ could not build module 'React'
  5 | 
  ```

**Comment by jpudysz** [comment]
Ok, I finally setup my local EAS 😂, working on a fix now
```
[RUN_FASTLANE] 
❌  (node_modules/react-native/React/Base/RCTBridge+Inspector.h:11:9)

   9 | 
  10 | #ifdef __cplusplus
> 11 | #import <jsinspector-modern/ReactCdp.h>
     |         ^ 'jsinspector-modern/ReactCdp.h' file not found
  12 | #endif
  13 | 
  14 | @interface RCTBridge (Inspector)

[RUN_FASTLANE] 
❌  (node_modules/react-native-unistyles/ios/Unistyles.h:4:9)

  2 | 
  3 | #import "jsi/jsi.h"
> 4 | #import <React/RCTUtils.h>
    |         ^ could not build module 'React'
  5 | 

[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
```

**Comment by mrousavy** [comment]
You need to add a dependency to whatever framework exposes RCTUtils and the inspector header you are using ;)

**Comment by ice-cap0** [comment]
Fixed? 🚀?

**Comment by jpudysz** [comment]
@ice-cap0 , you can also verify building from `main`. beta.2 will be released later this week
