### ISSUE TITLE
Theme isn't being registered

### ISSUE THREAD

**Issue by Pukimaa** [jpudysz/react-native-unistyles#374]
### Description

I get this error:
```
Metro error: Unistyles: You're trying to get theme "undefined" but it wasn't registered.

  10 | }
  11 |
> 12 | const styles = StyleSheet.create(theme => ({
     |                           ^
  13 |   container: {
  14 |     backgroundColor: theme.colors.surface.primary,
  15 |     flex: 1,
```

However when I remove the theming options from there and reload it works. Then when I add it back in and don't do a full refresh (meaning hot reload kicks in) it works fine and the colors work as expected, so my unistyles.ts must be loaded somehow.

I use Expo Router and Unistyles v3 and used the config from the Theming section in the docs and just changed the colors, but it also won't work if i don't change anything.

### Steps to Reproduce

1. Setup a project with Expo Router
2. Use the minimal config from the Theming section in the v3 docs
3. Use this code and apply it to a `View` for example:
```tsx
const styles = StyleSheet.create(theme => ({
  container: {
    backgroundColor: theme.colors.surface.primary,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
}));
```

### Snack or Repository Link (Optional)

Closed source. However I am more than happy to send over code snippets for specific files, if asked to.

### Unistyles Version

`3.0.0-beta.1`

### React Native Version

`0.76.3`

### Platforms

Web

### Expo

Yes

**Comment by kerwanp** [comment]
Had a similar issue. Make sure that:
- Your unistyle configuration is imported
- You have an initial theme configured
- **Both theme AND breakpoints are set**

In my case it was because I had no breakpoints configured.

```ts
StyleSheet.configure({
    settings: {
        initialTheme: 'light',
    },
    breakpoints,
    themes: appThemes
})
```

**Comment by qeude** [comment]
Same problem on my side, even though I'm doing everything as explained in the documentation

```
import { StyleSheet } from "react-native-unistyles";

const lightTheme = {
  colors: {
    primary: "#ff1ff4",
    secondary: "#1ff4ff",
  },
  gap: (v: number) => v * 8,
};

const darkTheme = {
  colors: {
    primary: "#aa12ff",
    secondary: "pink",
  },
  gap: (v: number) => v * 8,
};

const appThemes = {
  light: lightTheme,
  dark: darkTheme,
};

const breakpoints = {
  xs: 0,
  sm: 300,
  md: 500,
  lg: 800,
  xl: 1200,
};

type AppBreakpoints = typeof breakpoints;
type AppThemes = typeof appThemes;

declare module "react-native-unistyles" {
  export interface UnistylesThemes extends AppThemes {}
  export interface UnistylesBreakpoints extends AppBreakpoints {}
}

StyleSheet.configure({
  settings: {
    adaptiveThemes: true,
  },
  breakpoints,
  themes: appThemes,
});
```

**Comment by jpudysz** [comment]
Guys, you need to read docs better. For expo router there is one more requirement: https://www.unistyl.es/v3/guides/expo-router

**Comment by jpudysz** [comment]
> - **Both theme AND breakpoints are set**
> 
> 
> 
> In my case it was because I had no breakpoints configured.
> 

There is no such requirement, both are optional. If that's the case then it's bug.

**Comment by Pukimaa** [comment]
> Had a similar issue. Make sure that:
> 
>     * Your unistyle configuration is imported
> 
>     * You have an initial theme configured
> 
>     * **Both theme AND breakpoints are set**
> 
> 
> In my case it was because I had no breakpoints configured.
> 
> ```ts
> StyleSheet.configure({
>     settings: {
>         initialTheme: 'light',
>     },
>     breakpoints,
>     themes: appThemes
> })
> ```

Did all of that. Just used the default config provided in the docs.

**Comment by Pukimaa** [comment]
> Guys, you need to read docs better. For expo router there is one more requirement: https://www.unistyl.es/v3/guides/expo-router

I'm aware and followed these steps.

**Comment by nk711** [comment]
I had the same issue, I was just missing the following steps:

1. Add a `+html.tsx` file to the `app` folder.
2. Add the line `import '../assets/unistyles'` to the newly created file.

These instructions were detailed here:  https://www.unistyl.es/v3/guides/expo-router#static-rendering

Probably worth mentioning that the [expo example](https://github.com/jpudysz/react-native-unistyles/blob/main/expo-example/app/%2Bhtml.tsx) was pretty helpful. But it was missing the import line for it to work on the web 👍

**Comment by Pukimaa** [comment]
Hey! Yes, this fixed it. I was not really sure what the +html should contain and I wasn't even aware it uses static rendering. Thank you for your help :pray:

**Comment by Pukimaa** [comment]
Also I recommend importing the unistyles file in the `_layout.tsx`. That way you don't override any defaults and it still seems to work just fine.

**Comment by jpudysz** [comment]
Expo removed a lot of files from the SDK 52 starter. Like Babel config, +html etc. Not sure why..

**Comment by ferdinanddoremus** [comment]
I had the same problem.
Did read the expo docs.
Having a root index.js entry point as mentioned did not help.
I ended up importing unistyles config file at the root _layout file and it works (I do not use expo web).
