### ISSUE TITLE
Button Variant State Persistence Bug

### ISSUE THREAD

**Issue by FerVillanuevas** [jpudysz/react-native-unistyles#382]
### Description

When navigating between different screens that contain the Button component with different variants, the button styling from the next screen incorrectly persists and affects the button styling on the previous screen. This causes buttons to unexpectedly transform their variants based on navigation history rather than maintaining their defined variants.

### Steps to Reproduce

1. Click on any button 
2. change the button variant on the next screen (route)

see results

https://github.com/user-attachments/assets/9e90ac33-5c99-46bd-b955-7cd4dcdca644

### Snack or Repository Link (Optional)

https://github.com/FerVillanuevas/unibtn

### Unistyles Version

3.0.0-beta.1

### React Native Version

0.76

### Platforms

iOS

### Expo

Yes

**Comment by jpudysz** [comment]
I don't know yet what's going on, but it's about `Pressable`. For `TouchableOpacity` everything looks good.


https://github.com/user-attachments/assets/ac634c65-c7d0-4816-a90f-d8dc9529a53e

**Comment by FerVillanuevas** [comment]
Yeah! who needs Pressable ajaja

**Comment by jpudysz** [comment]
Regression on main

**Comment by jpudysz** [comment]
https://github.com/user-attachments/assets/4101650a-84f7-41e1-902e-b9e6c90168da
