### ISSUE TITLE
[v3] ImageBackground - Could not find shadow node for one of your components of type unknown

### ISSUE THREAD

**Issue by frankcalise** [jpudysz/react-native-unistyles#384]
### Description

While attempting to incrementally adopt `unistyles`, I ran into the following error:

`Unistyles: Could not find shadow node for one of your components of type unknown`

Note: I am not using RN's StyleSheet anywhere really, but just passing in plain objects to my style properties. I didn't have anything other than the import of my `unistyles.ts` breakpoint configuration being imported at the root of the app.

### Steps to Reproduce

1. Import `ImageBackground` from `react-native`
2. Render `ImageBackground`, like so:

 ```tsx
 <ImageBackground source={item.image} style={$imageContainer} imageStyle={$image} />
 
 // ... 
 
 const $image: ImageStyle = {
  flex: 1,
  resizeMode: "contain",
}
 ```
3. Observe error

### Unistyles Version

3.0.0-beta.1

### React Native Version

0.76.3

### Platforms

iOS

### Expo

Yes

**Comment by jpudysz** [comment]
Got it. The biggest issue is that, in this case I need to capture both the `View`'s ShadowNode and the `Image`'s ShadowNode.

In the video:
- The outer frame is attached to the `View`
- The inner frame is attached to the `Image`

Both respond to theme changes that swipe the border color. Still a WIP, but it's doable.

https://github.com/user-attachments/assets/f41e867e-7571-41e0-840c-775c31a0fa56

**Comment by frankcalise** [comment]
Ah nice! Sorry I could have provided more context, I definitely have a `<View />` around it

```tsx
const Item = ({ item }) => {
  const { width } = useWindowDimensions()
  return (
    <View style={[{ width }, $item]}>
      <View style={$imageBorder}>
        <ImageBackground source={item.image} style={$imageContainer} imageStyle={$image} />
      </View>
    </View>
  )
}
```
