### ISSUE TITLE
Benchmarking Performance

### ISSUE THREAD

**Issue by divineniiquaye** [jpudysz/react-native-unistyles#390]
### Description

In the benchmarking suite located at [react-native-style-libraries-benchmark](https://github.com/divineniiquaye/react-native-style-libraries-benchmark), In reporting this issue I made a mistake of rendering 250 items, Instead I was rendering 1000 items. After the fix I observed that **Unistyles v2 (stable)** and [**v3 (beta)**](https://github.com/divineniiquaye/react-native-style-libraries-benchmark/tree/unistyles-v3) performs great.

### **Actual Benchmark Results**

|UI                     | 1    | 2    | 3    | 4    | 5    | 6    | Avg     | % Slowdown |
|-----------------------|------|------|------|------|------|------|---------|------------|
| Native                | 696  | 738  | 711  | 712  | 726  | 684  | 711.27  | 0.00%      |
| Unistyles (v2 stable) | 668 | 698 | 693 | 691 | 712 | 722 | 697.33 | -1.96%     |
| Unistyles (v3 beta)   | 691 | 697 | 719 | 725 | 695 | 711 | 706.33 | -0.69%     |

### **Benchmark Results (1000 items) MISTAKE**

|UI                     | 1    | 2    | 3    | 4    | 5    | 6    | Avg     | % Slowdown |
|-----------------------|------|------|------|------|------|------|---------|------------|
| Native                | 696  | 738  | 711  | 712  | 726  | 684  | 711.27  | 0.00%      |
| Unistyles (v2 stable) | 2518 | 2850 | 2768 | 2785 | 2817 | 2971 | 2784.83 | 291.56%    |
| Unistyles (v3 beta)   | 2777 | 2953 | 2828 | 2822 | 2826 | 2912 | 2853.00 | 301.17%    |

### Steps to Reproduce

1. Clone the benchmark repository:  
   ```bash
   git clone https://github.com/divineniiquaye/react-native-style-libraries-benchmark.git
   ```
2. Install dependencies and set up the environment as per the README instructions.
3. Run the benchmarks on a device or emulator.
4. Observe the results for Unistyles.

### Snack or Repository Link (Optional)

https://github.com/divineniiquaye/react-native-style-libraries-benchmark

### Unistyles Version

3.x.x & 2.20.0

### React Native Version

0.76.x

### Platforms

iOS

### Expo

Yes

**Comment by divineniiquaye** [comment]
@jpudysz perhaps you can kindly spare some time to look into the benchmark repo on what I might be possibly doing wrong for such high slowdown.

I personally use this amazing library and like what has been done in v3. Since v3 is still in beta, I think this is worth investigating.

**Comment by jpudysz** [comment]
Thanks for the benchmarks,

I ran them 2–3 weekends ago and noticed a slowdown compared to StyleSheet, around ~10%. I haven’t optimized anything yet since 3.x still lacks some features.

I’m not sure why your numbers are significantly different or if I’ve made any changes in the meantime, but I don’t have an answer for now.

I’ll take a closer look at this aspect as we approach the RC. For now, it’s still too early. Keep in mind that Unistyles 3.0 isn’t stable or production ready yet.

PS

It would be good to mention what you are benchmarking in your table, e.g., the time for Unistyles 2 and the time for Unistyles 3 beta1. Right now, it’s unclear and might discourage some users who lack context.

**Comment by divineniiquaye** [comment]
> Thanks for the benchmarks,
> 
> I ran them 2–3 weekends ago and noticed a slowdown compared to StyleSheet, around ~10%. I haven’t optimized anything yet since 3.x still lacks some features.
> 
> I’m not sure why your numbers are significantly different or if I’ve made any changes in the meantime, but I don’t have an answer for now.
> 
> I’ll take a closer look at this aspect as we approach the RC. For now, it’s still too early. Keep in mind that Unistyles 3.0 isn’t stable or production ready yet.
> 
> PS
> 
> It would be good to mention what you are benchmarking in your table, e.g., the time for Unistyles 2 and the time for Unistyles 3 beta1. Right now, it’s unclear and might discourage some users who lack context.

v2 of unistyles is very fast, especially with the style provider added to the latest stable version of unistyles. In my benchmark, am looking out for:

1. Interactivity: Added TouchableOpacity for user interaction testing.
2. Dynamic Styling: Applied conditional styles for different backgrounds using style arrays.
3. Layout Configuration: Used flexbox properties to manage layout wrapping and spacing.
4. Content Addition: Included text inside each box for more realistic rendering scenarios.
5.  An array map of 250 count to render the above steps placed in a scrollview to also measure how it affects scrolling.

**Comment by efstathiosntonas** [comment]
@divineniiquaye what Jacek said it that you should explicity state that the Unistyles version you are using is beta and not a final product.

**Comment by jpudysz** [comment]
Yes, that’s what I meant. 💪

I have no problem being transparent, and as you can see, there’s a lot to improve!

We can test against this benchmark for every new beta when new optimizations are included.

Still, version 2.20 is stable and should be included in the benchmarks.

**Comment by jpudysz** [comment]
By the way, I checked the benchmark, and I do indeed get a similar output.  
When you `console.log` the `styles` before rendering any component, they are returned instantly from C++.  
The issue arises later when the `View` tries to access them. I can easily improve this and will try to add a fix before beta.2 or beta.3

**Comment by jpudysz** [comment]
Hey @divineniiquaye I think you made a big mistake. Unistyles 3 was rendered with 1000 elements vs other libs with 250 elements.

Performance is close to React Native:

![Screenshot 2024-12-04 at 09 59 04](https://github.com/user-attachments/assets/ec6d55ed-e4b7-4711-8d1b-144c44066c67)

https://github.com/divineniiquaye/react-native-style-libraries-benchmark/blob/1071bf57c226b840b9a4abbbde35968f797da9a5/components/Unistyles.js#L9

**Comment by efstathiosntonas** [comment]
@divineniiquaye I've hardcoded the 1000 on Unistyles.js while the rest pick the value from utils.js, it was easy to miss that :/. My bad.

**Comment by jpudysz** [comment]
Cool @divineniiquaye! 

Btw. would you consider increasing the number of views to 1000-2000?

There is no way Unistyles is faster with C++, memoization, shadow nodes than simple `StyleSheet`. I think we might see some difference with larger amount of views.

Also, would you consider another benchmark for switching theme? 
Some libs will do a full re-renders!
