### ISSUE TITLE
expo build fail for android

### ISSUE THREAD

**Issue by Keshav-1973** [jpudysz/react-native-unistyles#396]
### Description

build fails after running expo run:android

Execution failed for task ':react-native-unistyles:buildCMakeDebug[armeabi-v7a]'.

  FAILED: ../../../../build/intermediates/cxx/Debug/4m2n6q6n/obj/armeabi-v7a/libunistyles.so 

 C++ build system [build] failed while executing:
      /Users/keshav/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -C \
        /Users/keshav/Desktop/TGC_APP/TheGoldClass/node_modules/react-native-unistyles/android/.cxx/Debug/4m2n6q6n/armeabi-v7a \
        unistyles
    from /Users/keshav/Desktop/TGC_APP/TheGoldClass/node_modules/react-native-unistyles/android

  "dependencies": {
    "expo": "~52.0.15",
    "expo-status-bar": "~2.0.0",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-edge-to-edge": "^1.1.3",
    "react-native-nitro-modules": "^0.18.1",
    "react-native-unistyles": "^3.0.0-beta.1"
  },

### Steps to Reproduce

1. Create new expo blank app
2. Xcode Version: Version 16.1 (16B40)
3. Run yarn add react-native-unistyles@beta
yarn add react-native-nitro-modules react-native-edge-to-edge
4. Add to babel plugin
5. yarn expo prebuild --clean

### Unistyles Version

3.0.0

### React Native Version

0.76.3

### Platforms

Android

### Expo

Yes

**Comment by jpudysz** [comment]
Duplication of #373
