### ISSUE TITLE
[v3] Issues with expo router entry when using yarn workspaces monorepo

### ISSUE THREAD

**Issue by samducker** [jpudysz/react-native-unistyles#397]
### Description

I'm currently in process of moving to v3

When using expo router and following the documentations guidance to change the main key in package.json to 

index.js
```
import 'expo-router/entry';
import './constants/unistyles'; // my unistyles path
```
My navigator no longer gets registered, if I revert back to the "main": "expo-router/entry" navigation registration works fine however unistyles will then throw the error that configure has not been called early enough even if I put it right at the top of my imports of my root _layout.tsx

Error msg
```
Couldn't register the navigator. Have you wrapper your app with 'NavigationContainer'?
```

Additional context
I'm not sure if it is related but I'm using yarn classic workspaces in a monorepo setup. 

### Steps to Reproduce

1. Take an expo router project in yarn workspaces with typescript 
2. Modify entry point to index.js as per docs
3. Try to run with clean build on iOS real device

### Unistyles Version

3.0.0 (main branch)

### React Native Version

0.76.3

### Platforms

Android, iOS

### Expo

Yes

EDIT:

None of the solutions have worked for me just yet but I'm following this github issue also
https://github.com/expo/router/issues/41

**Comment by dhruvpvx** [comment]
make sure you have added
`"main": "index.js",`
in you package.json

and 

`export { default } from 'expo-router/entry';`

in index.js

**Comment by samducker** [comment]
This approach doesn't work for me, neither does the one listed in the docs. 

I get the same error 

```
Couldn't register the navigator. Have you wrapper your app with 'NavigationContainer'?
```

If I put the "main": "expo-router/entry" it does not have issues with the navigator, but then the unistyles configure is not registered early enough by putting it in _layout.tsx

**Comment by dhruvpvx** [comment]
Can you share your package.json and index.js file?

**Comment by samducker** [comment]
It is exactly what the docs stated, and then I also tried what you stated. 

I've managed to resolve the issue by setting the project inside the monorepo to be set as nohoist in my yarn workspaces root package.json.

Previously I had it hoisting shared dependancies to the top of the monorepo which was working fine with the official expo instructions.

**Comment by jpudysz** [comment]
Thanks for the update.  
I was testing it with the bare Expo Router starter, so setting it up in a monorepo would require some additional adjustments.  
The only requirement for Unistyles is that it must be installed before you attempt to access the `StyleSheet` with the theme for the first time. I used `console.log` to confirm the file execution order.  

I believe there's nothing to patch or update here, as this is a project specific issue.

**Comment by samducker** [comment]
Agree - looks like a monorepo + Expo router issue rather than Unistyles itself. We can close.

If I find a no-nohoist solution later, we can add monorepo setup guidance to the docs as a note perhaps to make their experience smoother.

The default Expo recommend monorepo setup was working fine before the Unistyles entry point changes.​​​​​​​​​​​​​​​​

**Comment by jpudysz** [comment]
This is now fixed. 
You can use `useUnistyles` - https://www.unistyl.es/v3/references/use-unistyles
This method **won't** re-render your screens.
