### ISSUE TITLE
[3.0.0-beta.2] `UnistylesRuntime.getTheme()` returns never

### ISSUE THREAD

**Issue by jeremybarbet** [jpudysz/react-native-unistyles#423]
### Description

Hi there,

Looks like beta.2 is breaking `UnistylesRuntime.getTheme()` and no type is returned

### Steps to Reproduce

1. `yarn create expo-app`
2. `yarn add react-native-unistyles@beta react-native-nitro-modules react-native-edge-to-edge -E` and do required setup
3. Try to access:
```tsx
const theme = UnistylesRuntime.getTheme()
//                             ^ (property) UnistylesRuntimeBuilder.getTheme: (themeName?: undefined) => never
```

### Snack or Repository Link (Optional)

https://github.com/jeremybarbet/unistyles-runtime-get-theme

### Unistyles Version

3.0.0-beta.2

### React Native Version

0.76.5

### Platforms

iOS

### Expo

Yes

**Comment by jpudysz** [comment]
Thanks for the report, we switched default resolution to `web` files instead of `native`. We need to update the types.

**Comment by Brentlok** [comment]
In the meantime this patch should fix your issue 😄 
[react-native-unistyles+3.0.0-beta.2.patch](https://github.com/user-attachments/files/18122741/react-native-unistyles%2B3.0.0-beta.2.patch)

**Comment by jeremybarbet** [comment]
Great, will give it a try later in the day, 

cheers!
