### ISSUE TITLE
Unable to combine 'as const' with 'satisfies' when creating a theme

### ISSUE THREAD

**Issue by dehcastro** [jpudysz/react-native-unistyles#425]
### Description

Hey!

Today I came across an issue while trying to make use of a const assertion and narrow its values down but at the same time being able to type it. 

```typescript
// types.ts
import { TextStyle } from 'react-native'

type TypographyStyle = Pick<TextStyle, 'fontFamily'>

type TypographyOptions = 'headline-1' | '...'

export type Typography = { [key in TypographyOptions]: TypographyStyle }

// ----------

// typography.ts
export const typography = {
  'headline-1': {
    fontFamily: 'font-name',
    // ...
  }
} as const satisfies Typography
```  
In the code above, combining `as const satisfies Typography` does the trick, vscode intellisense is able to suggest values for the `const typography`.   

![image](https://github.com/user-attachments/assets/f7002c17-2ffc-468c-8c69-767d8237f3dd)

But when adding typography to the theme, it does not suggest typography options:

![image](https://github.com/user-attachments/assets/c8a082df-6875-4e88-9e22-c22771a99f61)

Now, if I keep only the `as const` (remove the `satisfies Typography`), then it suggests values:

![image](https://github.com/user-attachments/assets/aa92976c-4660-4ea8-93f0-d1a7405dba74)

Is there a way to type our themes and also get assertions by narrowing values down?

### Steps to Reproduce

1. Create an expo project and install `react-native-unistyles`
2. Create a theme:
```typescript
import { UnistylesRegistry } from 'react-native-unistyles'
import { TextStyle } from 'react-native'

type TypographyStyle = Pick<TextStyle, 'fontFamily'>

type TypographyOptions = 'headline-1'

export type Typography = { [key in TypographyOptions]: TypographyStyle }

const typography = {
  'headline-1': {
    fontFamily: 'font-family-name',
  },
} as const satisfies Typography

const darkTheme = {
  colors: {
    //...
  },
  typography,
}

type AppThemes = {
  dark: typeof darkTheme
}

declare module 'react-native-unistyles' {
  export interface UnistylesThemes extends AppThemes {}
}

UnistylesRegistry.addThemes({
  dark: darkTheme,
}).addConfig({ initialTheme: 'dark' })
```
3. try to access the theme values in your components

### Unistyles Version

2.20.0

### React Native Version

0.76.5

### Platforms

Android, iOS

### Expo

Yes

**Comment by Brentlok** [comment]
Hi,

I tried your example, and it works both with and without `as const` in TypeScript 5.7.2.

Could you provide more context on why you're adding `as const` here? Using `satisfies` alone seems to achieve your goal. `as const` merely makes the properties readonly.

![image](https://github.com/user-attachments/assets/90056883-9efc-47bf-b210-080512ad8895)
![image](https://github.com/user-attachments/assets/8c8d587a-9bf1-4634-9945-15679c1dd9f3)

**Comment by dehcastro** [comment]
hi! I'm using the same typescript version but I still cannot get the values assertion

![image](https://github.com/user-attachments/assets/2e9f4564-3390-4681-bdb9-0b88e40bccb9)

as you can see above, `typography` only information is that it's of `Typography` type, on the other hand you see that the intellisense is able to tell what colors are under the token `colors`

**Comment by jpudysz** [comment]
That's cool, thanks for the update! 🎉
