### ISSUE TITLE
adaptive theme not properly display dark theme

### ISSUE THREAD

**Issue by chanphiromsok** [jpudysz/react-native-unistyles#426]
### Description

I encounter that when I use the system default to dark and open the app it displays a light theme background white -> flash to dark theme 

https://github.com/user-attachments/assets/c96297ef-2a40-4a0f-8f8d-ccd014ef03f6

### Steps to Reproduce

set system to dark in android -> open the app -> see flash light theme -> display dark theme

### Unistyles Version

3.0.0-beta.2

### React Native Version

0.76.5

### Platforms

Android

### Expo

Yes

**Comment by jpudysz** [comment]
Hey can you check against `beta.4`? You didn't provide a repro, so It's hard to verify on my side.

**Comment by chanphiromsok** [comment]
I try beta4 still the same repo https://github.com/chanphiromsok/asdf-tr/tree/unistyle-v3

**Comment by chanphiromsok** [comment]
Hi @jpudysz I think the flash white background is from the splash screen on Android I test on pixel it hides with the  background white then launched the screen is correct behavior

**Comment by jpudysz** [comment]
I think you need to have `png` icon, because if this one has a background then it will be always white 🤔 

So is there anything I can do or we can close?

**Comment by chanphiromsok** [comment]
> I think you need to have `png` icon, because if this one has a background then it will be always white 🤔 
> 
> 
> 
> So is there anything I can do or we can close? 

yes I think can close
