### ISSUE TITLE
Server Error Unistyles: You're trying to get theme "undefined" but it wasn't registered.

### ISSUE THREAD

**Issue by NeRo8** [jpudysz/react-native-unistyles#431]
### Description

I create application for testing last version of unistyles

Github repository [TestApplication](https://github.com/NeRo8/TestApplication)

## What steps I made, before get a crash

1. Install clear expo project `npx create-expo-app@latest`
2. Reset project `npm run reset-project`
3. Install unistyles `yarn add react-native-unistyles@beta react-native-nitro-modules react-native-edge-to-edge`
4. Modify my `babel.config.js`
5. Create root index.js file
6. Run `npm run start`
7. Run on web

After web application run I see this message `Server Error Unistyles: You're trying to get theme "undefined" but it wasn't registered.`

### Steps to Reproduce

1. `npm install`
2. `npm start`

### Snack or Repository Link (Optional)

https://github.com/NeRo8/TestApplication

### Unistyles Version

3.0.0-beta.2

### React Native Version

0.76.5

### Platforms

Web

### Expo

Yes

**Comment by jpudysz** [comment]
Fixed in beta.3

**Comment by mrtawil** [comment]
I am facing the same issue on version `^3.0.0-beta.4`

**Comment by jacobarvidsson** [comment]
I am facing the same issue on version ^3.0.0-beta.4 as well.

**Comment by Timothy-Anders0n** [comment]
As do I

**Comment by Braedan** [comment]
Same issue here on beta.4. @NeRo8 were you able to get your example working with the beta.3 release?

**Comment by PierreCapo** [comment]
For those who still have the issue with Expo Router, you need to follow the doc as aforementioned: https://www.unistyl.es/v3/guides/expo-router/#static-rendering

**AND** do the same also for the `app/_layout.tsx` file:
```Typescript
// app/_layout.tx
import '../unistyles' // <-- file that initializes Unistyles$
```
