### ISSUE TITLE
[v3] Support react-native-nitro-modules v0.19.0 (Android)

### ISSUE THREAD

**Issue by giovannilondero** [jpudysz/react-native-unistyles#457]
### Description

Following the [documentation](https://www.unistyl.es/v3/start/getting-started#installation), at the moment react-native-nitro-modules v**0.19.0** is installed, but it breaks the Android build.

Works with v0.18.2.
Not tested on iOS.

### Steps to Reproduce

1. move to the provided repository (branch `nitro-0.19.0`)
2. run the app (`npm i`, `npx expo run:android --no-build-cache`)

### Snack or Repository Link (Optional)

https://github.com/giovannilondero/unistyles-boxshadow/tree/nitro-0.19.0

### Unistyles Version

3.0.0-beta.4

### React Native Version

0.76.5

### Platforms

Android

### Expo

Yes

**Comment by jpudysz** [comment]
Hey @giovannilondero, Nitro Modules v0.19 introduced some breaking changes for library authors. This time, it's not as easy as just bumping the version. I need to regenerate the files and follow the upgrade guide.  

Keep in mind that Unistyles always ships with the latest Nitro Module version. Marc released it yesterday. The last Unistyles version was released a few days ago.  

This is not an issue per se, I will for sure upgrade Nitro with the next Unistyles release!

**Comment by giovannilondero** [comment]
Thank you @jpudysz 

Would it be possible to add a table with known supported versions in the docs, under the installation instructions?
Even something like this, if it doesn't require you much time:
| Unistyles | Nitro Modules |
|--------|--------|
| 3.0.0-beta.4 | ^0.18 | 

I get it's still in beta and moving quickly, but it seems to be getting so much traction, it might help.
You do you, I'll still support the decision :D

**Comment by jpudysz** [comment]
This is the first time it has a breaking change, if it continues we can add this note to the docs 🙏
