### ISSUE TITLE
Defining the same variant across multiple styles not working

### ISSUE THREAD

**Issue by fabcstro** [jpudysz/react-native-unistyles#459]
### Description

Hello!

I am implementing a stylesheet with 3 styles, each one of them is implementing the same variants as described in the documentation: [https://v2.unistyl.es/reference/variants/#defining-the-same-variant-across-multiple-styles](url)

However, the inferred type is not being consolidated, causing problems when trying to extend the type in an interface.

### Steps to Reproduce

Code to reproduce:
```typescript
const stylesheet = createStyleSheet(theme => ({
  root: {
    justifyContent: 'center',
    alignItems: 'center',

    variants: {
      orientation: {
        horizontal: {
          flexDirection: 'row',
          marginVertical: 20,
        },
        vertical: {
          flexDirection: 'column',
          marginHorizontal: 20,
        }
      }
    }
  },
  line: {
    flex: 1,
    backgroundColor: theme.colors.border,

    variants: {
      orientation: {
        horizontal: {
          height: 1
        },
        vertical: {
          width: 1
        }
      }
    }
  },
  text: {
    color: theme.colors.border,
    
    variants: {
      orientation: {
        horizontal: {
          marginHorizontal: 10,
        },
        vertical: {
          marginVertical: 10,
        }
      }
    }
  }
}));

type DividerVariants = UnistylesVariants<typeof stylesheet>;
```
Infered type:
<img width="428" alt="image" src="https://github.com/user-attachments/assets/30139cd2-f1f0-41f4-8114-d81ba2d72383" />

Error:
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/cd8b921a-54e7-4202-8baa-2c0284c7092b" />

### Unistyles Version

2.20.0

### React Native Version

0.76.3

### Platforms

Android, iOS, Web

### Expo

Yes

**Comment by jpudysz** [comment]
Hey @fabcstro this is how TypeScript work and we can't do anything about it.

https://www.totaltypescript.com/concepts/an-interface-can-only-extend-an-object-type

To fix it, change `interface` to `type` and all the types will be inferred correctly.
