### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by AntonioLoco** [jpudysz/react-native-unistyles#460]
### Description

When I try to start the app on IOS with the expo run:ios command, it goes into error. 

❌  (node_modules/react-native-unistyles/nitrogen/generated/ios/swift/HybridNativePlatformSpecCxx.swift:80:36)

  78 |     @inline(__always)
  79 |     get {
> 80 |       return self.__implementation.hybridContext
     |                                    ^ value of type 'any HybridNativePlatformSpec' has no member 'hybridContext'
  81 |     }
  82 |     @inline(__always)
  83 |     set {

❌  (node_modules/react-native-unistyles/nitrogen/generated/ios/swift/HybridNativePlatformSpecCxx.swift:84:29)

  82 |     @inline(__always)
  83 |     set {
> 84 |       self.__implementation.hybridContext = newValue
     |                             ^ value of type 'any HybridNativePlatformSpec' has no member 'hybridContext'
  85 |     }
  86 |   }
  87 | 

### Steps to Reproduce

1. Create Expo App
2. Install Unistyles
3. Run expo run:ios

### Unistyles Version

^3.0.0-beta.4

### React Native Version

0.76.5

### Dependencies
  "dependencies": {
    "expo": "~52.0.20",
    "expo-alternate-app-icons": "^1.1.0",
    "expo-constants": "~17.0.3",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.14",
    "expo-splash-screen": "~0.29.18",
    "expo-status-bar": "~2.0.0",
    "react": "18.3.1",
    "react-native": "0.76.5",
    "react-native-edge-to-edge": "^1.1.3",
    "react-native-gesture-handler": "~2.21.2",
    "react-native-nitro-modules": "^0.19.0",
    "react-native-reanimated": "~3.16.5",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.3.0",
    "react-native-unistyles": "^3.0.0-beta.4"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/react": "~18.3.12",
    "prettier": "^3.4.2",
    "typescript": "^5.3.3"
  },

### Platforms

iOS

### Expo

Yes

**Comment by jpudysz** [comment]
Hey, it's because you installed Nitro 0.19 that was released yesterday and it has some breaking changes for library authors. 

Unistyles beta.4 was released few days ago and it supports version 0.18.2:

https://github.com/jpudysz/react-native-unistyles/blob/0fadf2d4ed2ce899a167384f9966cc1f267b15c7/package.json#L95

I have no plans to release beta.5 during Christmas and New Year Eve, so you need to downgrade to 0.18.2.

**Comment by AntonioLoco** [comment]
> Hey, it's because you installed Nitro 0.19 that was released yesterday and it has some breaking changes for library authors.
> 
> Unistyles beta.4 was released few days ago and it supports version 0.18.2:
> 
> https://github.com/jpudysz/react-native-unistyles/blob/0fadf2d4ed2ce899a167384f9966cc1f267b15c7/package.json#L95
> 
> I have no plans to release beta.5 during Christmas and New Year Eve, so you need to downgrade to 0.18.2.

@jpudysz oh excuse me for the issue, I didn’t know

**Comment by jpudysz** [comment]
No worries! I will align it with `beta.5` ☺️

**Comment by MetinArslanturk** [comment]
Oh, got same error and I was about to open a new issue. Then found this issue.

Yeah NitroModules version downgrading solved the issue. But it seems, everyone who is following getting-start docs will get this error from today. So it will create a lot headache on you until it :) @jpudysz you may think to update docs (temporarily) to prevent this.

**Comment by Timothy-Anders0n** [comment]
> Oh, got same error and I was about to open a new issue. Then found this issue.
> 
> Yeah NitroModules version downgrading solved the issue. But it seems, everyone who is following getting-start docs will get this error from today. So it will create a lot headache on you until it :) @jpudysz you may think to update docs (temporarily) to prevent this.

Same, got the issue from following the docs but found this issue before opening my own.
