### ISSUE TITLE
Incomplete color normalization

### ISSUE THREAD

**Issue by levibuzolic** [jpudysz/react-native-unistyles#52]
### Description

The new color normalization added in #50 has broken `react-native-web` shadow styling for some colour formats.

https://github.com/jpudysz/react-native-unistyles/blob/86534364771264941c63496d32421bc1a4c04706/src/utils/normalizer.ts#L11-L13

Based on the comments in the commit it looks like it's known that it's an incomplete implementation.

I imagine to stay in-sync with what React Native itself supports, it'd make sense to add a `peerDependency` to [@react-native/normalize-colors](https://www.npmjs.com/package/@react-native/normalize-colors) which is the underlying utility library that React Native uses to pre-parse colours and then mix-in the alpha channel where required.

I'd be happy to create a PR with that implementation if that approach is suitable.

### Steps to reproduce

1. Use a `shadowColor` of `black` with an opacity of `0.5`
2. Observe output colour is `black` without opacity

### Unistyles version

1.1.0

### React Native version

0.72.6

### Platforms

React Native Web

**Comment by jpudysz** [comment]
I wasn't aware of that! I also didn't know about this lib. I will happily accept the PR 🙏
