### ISSUE TITLE
Can't build on EAS since the node version is locked on v18 but EAS is using v16.18.1

### ISSUE THREAD

**Issue by Albert-Gao** [jpudysz/react-native-unistyles#56]
### Description

![image](https://github.com/jpudysz/react-native-unistyles/assets/18282328/3facc074-9390-4f80-ad37-62005496a574)

https://github.com/jpudysz/react-native-unistyles/blob/af5256c3ad8539072a6c8728220da86eac5be4d8/package.json#L95

We really need v18 for this? :)

### Steps to reproduce

```bash
eas build
```

### Unistyles version

1.1.1

### React Native version

0.72.6

### Platforms

iOS

**Comment by jpudysz** [comment]
Hello Albert,

Node 16 has been deprecated since September 11. You can now use Node 18 in your EAS. Please follow this link: https://expo.dev/changelog/2023/11-03-node-default.

Enjoy your weekend! 🙌
