### ISSUE TITLE
box shadows on iOS not working

### ISSUE THREAD

**Issue by FrancoTanzarellaEviivo** [jpudysz/react-native-unistyles#6]
Thanks for the library. I'm excited to see this get to an official release soon.

I've run into this small issue. Not sure if it is something on my end I'm missing but box shadows on iOS are not being applied correctly. Changing the offset width and height has no effect.

When I apply the same to the button directly I get the expected results.

```javascript
const stylesheet = createStyles((theme) => ({
  padButton: {
    backgroundColor: theme.colours.white,
    borderRadius: 30,
    elevation: 14,
    shadowColor: theme.colours.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    height: PAD_WIDTH,
    width: PAD_WIDTH,
    justifyContent: 'center',
  },
}));

**Comment by jpudysz** [comment]
Hey @FrancoTanzarellaEviivo thank you for the bug report.

I was able to reproduce it, fix incoming in few minutes
