### ISSUE TITLE
SSR media query hydration error

### ISSUE THREAD

**Issue by HellYeahOmg** [jpudysz/react-native-unistyles#61]
### Description

Hydration error with media queries:
![image](https://github.com/jpudysz/react-native-unistyles/assets/29250449/9eb80e5c-47bd-4d30-85c1-cb1a09acb6e7)

Component:
`<View style={styles.linksContainer}> ... </View>`

Styles:
`linksContainer: { display: { xs: 'none', xl: 'flex', }, flexDirection: 'row', },

On the first render on the desktop (xl size) the linksContainer is hidden, even though it shouldn't be. Moreover, if I resize the window to a smaller, and then to a larger screen size (xl+), the media query seems to start working.

### Steps to reproduce

I'm using https://solito.dev/expo-router started pack. 
Installed unistyles to packages/app directory.
Write a component with some css media queries.

### Unistyles version

1.1.1

### React Native version

-

### Platforms

React Native Web

**Comment by jpudysz** [comment]
Thank you @HellYeahOmg for the report. It was easy to fix, but hard to spot 😄

**Comment by HellYeahOmg** [comment]
Even though it fixed the issue, I can still see an error in the console:
<img width="1082" alt="Screenshot 2023-11-06 at 12 52 14" src="https://github.com/jpudysz/react-native-unistyles/assets/29250449/08150609-4e5f-4886-8afa-71b7e4fd946a">

` linksContainer: {
    // display: 'flex',
    display: {
      xs: 'none',
      xl: 'flex',
    },
    flexDirection: 'row',
  },`

**Comment by jpudysz** [comment]
Let me try to repro it 👀

**Comment by jpudysz** [comment]
Yeah, I have a repro.
I missed this part:

`On the first render on the desktop (xl size) the linksContainer is hidden, even though it shouldn't be.`

**Comment by jpudysz** [comment]
Patched, will be available in ~10 minutes.

**Comment by jpudysz** [comment]
Please try with 1.1.3

**Comment by HellYeahOmg** [comment]
Xd it became worse. Now the simple code breaks down everything (no styles at all):
`<View>
      <Text>lorem</Text>
    </View>`

<img width="1120" alt="image" src="https://github.com/jpudysz/react-native-unistyles/assets/29250449/e6b6241a-4b30-4ebb-b720-f7a6fbe8b815">

**Comment by jpudysz** [comment]
Ok, fixed and released in 1.1.4.

Keep in mind that in version 1.0 unistyles breakpoints live on JS side. So you may expect https://web.dev/articles/cls

Here is a way to address it:
https://github.com/jpudysz/react-native-unistyles-ssr-exmaple/commit/9d809add121e811b24409879399fb857da7bd347

With next versions I will move it to media queries so it will have no CLS.

**Comment by HellYeahOmg** [comment]
Works like a charm! 
Tho the solution with isClient is probably gonna kill your seo?

**Comment by jpudysz** [comment]
Yeah, you can also fix it with some global loader (on first load):

```tsx
{!isClient && (
    <View style={styles.loader}>
        <ActivityIndicator />
    </View>
)}
```

```ts
const stylesheet = createStyleSheet(theme => ({
    loader: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.backgroundColor
    }
})
```

It will be displayed only once, but you gonna get full HTML content. 
To fix this I'm need to move media queries to CSS.
I've added it to todo list for 2.0


https://github.com/jpudysz/react-native-unistyles/assets/9088288/593610db-aa1b-4581-a24f-df98c9acd3ec
