### ISSUE TITLE
"Cannot convert undefined or null to object" when `shadowOffset` is undefined

### ISSUE THREAD

**Issue by hbriese** [jpudysz/react-native-unistyles#66]
### Description

The error `Cannot convert undefined or null to object` is thrown when `shadowOffset` style is present by undefined

### Steps to reproduce

```ts
function useTest() {
    useStyles(stylesheet);
}

const stylesheet = createStylesheet({
    test: {
        shadowOffset: undefined,
    },
});
```

### Unistyles version

1.1.1

### React Native version

0.72.5

### Platforms

Android, iOS, React Native Web

**Comment by jpudysz** [comment]
Thanks for the report @hbriese and for finding this case.

**Comment by jpudysz** [comment]
Fxied in #69
