### ISSUE TITLE
Feature: Add support breakpoint for object style

### ISSUE THREAD

**Issue by MasonLe2497** [jpudysz/react-native-unistyles#8]
Currently, this ```parseStyle``` function return object style without breakpoint
We need to support object style: transform, shadowOffset, transformOrigin, ...

**Comment by jpudysz** [comment]
Hey, I've just added support for arrays (`transform`) and `shadowOffset`. Fell free to improve it for `transformOrigin`. Also please check #10

**Comment by jpudysz** [comment]
Moved to #13
