### ISSUE TITLE
Quick glitch/transition showing light mode temporarily (when I am already in dark mode)  - when refreshing or first loading the page in react native web (via expo)

### ISSUE THREAD

**Issue by ammarfaris** [jpudysz/react-native-unistyles#82]
### Description

Quick glitch/transition showing light mode temporarily (when I am already in dark mode)  - when refreshing or first loading the page in react native web (via expo) ; toggling dark-light mode via the actual dark-light mode toggle works fine

https://github.com/jpudysz/react-native-unistyles/assets/1182205/acc7eccf-fb9c-4d47-a7da-39e273e5f670

### Steps to reproduce

1. Run `npx create-expo-app my-app` and choose Navigation (Typescript) for expo-router version
2. Follow the setup guide at unistyles [setup page](https://reactnativeunistyles.vercel.app/start/setup/)
3. Add code to test light-dark mode (sample given in unistyles doc)
4. Run `yarn web` and try to refresh the web page

### Unistyles version

2.0.0

### React Native version

0.72.6

### Platforms

React Native Web

### Engine

Hermes

### Architecture

Paper (old)

**Comment by jpudysz** [comment]
Should be easy to fix, thank you for the report 🙇‍♂️

**Comment by jpudysz** [comment]
Hello,

I was unable to reproduce your issue.

I have created a repository with the correct setup: https://github.com/jpudysz/react-native-unistyles-expo-router.

You just need to avoid mixing Expo's theming with Unistyles. In this repository, everything is converted to Unistyles and works as intended.

**Comment by ammarfaris** [comment]
> Hello,
> 
> I was unable to reproduce your issue.
> 
> I have created a repository with the correct setup: https://github.com/jpudysz/react-native-unistyles-expo-router.
> 
> You just need to avoid mixing Expo's theming with Unistyles. In this repository, everything is converted to Unistyles and works as intended.

Thanks @jpudysz  for creating the repository, appreciate it very much!

My apology -  I missed one information, I was also testing Expo SDK 50 Beta + Expo Router v3 Beta at that time and I just realized that I have upgraded my project to Expo SDK 50 Beta by running commands below - from  "Using the Beta" section in this [announcement page](https://blog.expo.dev/expo-router-v3-beta-is-now-available-eab52baf1e3e):

```yarn add expo@next```

```npx expo install --fix```  

So when I run that in your repo, the flickering / glitch came back ; Maybe once SDK50 is out of Beta, we can revisit this. Thanks for your help and effort!

**Comment by jpudysz** [comment]
No worries! I'm glad that I could narrow the issue to V3

**Comment by annidai** [comment]
Hi @jpudysz , I’m also experiencing the same issue with Expo SDK 50 and Expo-router v3. Now that SDK 50 is officially released, would it be more appropriate to open a new issue or should we consider reopening this one?

**Comment by jpudysz** [comment]
Hey, can you create a repro with v3? I don't think it's Unistyles issue as it provides colors before the render, maybe something specific for the Expo Router.

**Comment by annidai** [comment]
> Hey, can you create a repro with v3? I don't think it's Unistyles issue as it provides colors before the render, maybe something specific for the Expo Router.

Hey @jpudysz, after taking a closer look, it seems that setting the system UI background and applying a background color to the root stack resolves the issue. Thank you for the help!

**Comment by jpudysz** [comment]
You resolved the mystery of Expo Router v3! Thank you for your reply! ❤️
